### ISSUE TITLE
Outdated content on INSTALL file

### ISSUE THREAD

**Issue by mjmg** [cdeterman/gpuR#101]
The INSTALL file indicates that the gpuR package is for Linux systems only but I think the package builds and works on Windows systems also for some time. ;)

This might turn off potential users in Windows when looking at the CRAN page unless they check the github page and wiki.

https://github.com/cdeterman/gpuR/blob/master/INSTALL

**Comment by cdeterman** [comment]
You are correct, I will make a point to update this.  Thank you.
