### ISSUE TITLE
GEMM operations - benchmark R code

### ISSUE THREAD

**Issue by f0nzie** [cdeterman/gpuR#102]
Hello Charles,
I love `gpuR `. It just installs out of the bat in my Windows 10 with Nvidia Quadro K2100M.

I couldn't find the R code that you used in your article here http://www.parallelr.com/r-gpu-programming-for-all-with-gpur/.

Wouldn't you mind sharing it, please?
Thanks.

**Comment by cdeterman** [comment]
Thanks for the compliments and I'm glad to here the install is working well for Windows.  Regarding the benchmarks (which I assume you are referring) you can find the code in another one of my repositories [here](https://github.com/cdeterman/gpuRbenchmark).  Keep in mind, the `vclMatrix` calls are asynchronous so they are somewhat misleading as it returns immediately and you can continue on with your processing (while the GPU computation progresses).  If you want to truly benchmark them you will need to add a `synchronize()` call after whatever operation you are benchmarking.

**Comment by f0nzie** [comment]
Thanks.
I tried to build this in Windows 10 but I get this error:
![image](https://user-images.githubusercontent.com/29108853/34220157-34758556-e579-11e7-8c4f-61673d165c52.png)

**Comment by cdeterman** [comment]
@f0nzie since this is related to gpuRbenchmark it should be reported there.  I have created an issue [here](https://github.com/cdeterman/gpuRbenchmark/issues/1).  I will provide updates there.
