### ISSUE TITLE
chol cannot be called using::

### ISSUE THREAD

**Issue by VictorPPB** [cdeterman/gpuR#106]
This issue is directly related to  [#83](https://github.com/cdeterman/gpuR/issues/83).

I want to use `chol` or `chol.vclMatrix` in inside another package. But I get the following:

`gpuR::chol.vclMatrix
Error: 'chol.vclMatrix' is not an exported object from 'namespace:gpuR'`

After listing all the functions inside gpuR with `ls("package:gpuR")`, `chol` is not there. ¿How can I use `chol` from gpuR inside another package?

**Comment by cdeterman** [comment]
Do you have a repository for this that I could fork to try and reproduce?

**Comment by VictorPPB** [comment]
We don't have a package repository yet. But the problem is just as described. ¿Is there a way you can help me without the repo?

**Comment by cdeterman** [comment]
I can try and create my own, it will just take a little more time.  When I have some extra availability I will give it a go and see if I can reproduce the problem.

**Comment by VictorPPB** [comment]
The repo may not be needed, this example shows the problem:

`mm<- matrix(rnorm(100*100),ncol=100,nrow=100)`
`ch_gpu <- gpuR::svd(mm, nv = 0)`
`ch_gpu1 <- gpuR::chol(mm, nv = 0)`

And I get:

`Error: 'chol' is not an exported object from 'namespace:gpuR'`

**Comment by cdeterman** [comment]
That is because you are trying to call `chol` on a `base::matrix` object.  The `chol` within `gpuR` is an S3 method so it is actually defined as `chol.gpuMatrix` or `chol.vclMatrix`.  You simply need to create a `gpuMatrix`/`vclMatrix` and call `chol` normally.  The S3 dispatch should find the appropriate method in the `gpuR` namespace.  The following should work.

```r
gm <- gpuR::gpuMatrix(matrix(rnorm(16), 4, 4)), type = "float")
ch_gpu <- chol(gm)
```

**Comment by VictorPPB** [comment]
You're right about the object passed (sorry about that). But since I need to use chol from `gpuR`, I need something like `gpuR::chol`. It should work as it does with `gpuR::svd`, like this:

`gm <- gpuR::gpuMatrix(matrix(rnorm(16), 4, 4), type = "float");
ch_gpu <- gpuR::chol(gm);
ch_gpu <- gpuR::svd(gm)`

But it doesn't with `gpuR::chol`

**Comment by cdeterman** [comment]
You misunderstand, `chol` is an S3 method and `svd` I defined as an `s4` method.  As such, the base `svd` method is exported but `chol` is not.  It will automatically call the internal `gpuR::chol` method when `chol` is executed on a `gpuR` object.  Ergo, you do not need to prefix the `gpuR` namespace in that instance.

**Comment by VictorPPB** [comment]
Thanks! It clear now.
