### ISSUE TITLE
gpuR as an optional dependency (Travis woes)

### ISSUE THREAD

**Issue by agrueneberg** [cdeterman/gpuR#116]
I would like to add optional GPU support to one of my packages. After adding gpuR to `Suggests:`, `R CMD check` fails on platforms without GPU support such as Travis because it automatically installs optional dependencies and tries to load them (unless `_R_CHECK_FORCE_SUGGESTS_` is set to false, which may not be an option). On Travis, the missing OpenCL library needed during linking can be addressed by installing the `ocl-icd-opencl-dev` package via APT, but it is my understanding that the call to `initContexts()` in `.onAttach()` will only succeed if something like POCL is installed and for that a custom .travis.yml is needed, which is quite a burden for an optional feature. Do you have any suggestions?

**Comment by cdeterman** [comment]
Unfortunately I don't believe there is a way to accomplish this.  AFAIK, R requires the loading of `Suggests:` and is also noted by Dirk [here](https://stackoverflow.com/questions/29178171/travis-ci-r-suggested-package).  That said, I run unit tests of Travis CI using `gpuR`.  If you wish, you can use the the majority of my `.travis.yml` script [here](https://github.com/cdeterman/gpuR/blob/develop/.travis.yml) and that will install POCL for you.
