### ISSUE TITLE
install gpuR in Anaconda

### ISSUE THREAD

**Issue by 08walshth** [cdeterman/gpuR#122]
Installing `gpuR` in Anaconda on a Windows 10 machine.

The `install packages` wizard has `gpuR ` pre-loaded when searching, but installing returns this error:

    Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘gpuR’

I have also tried downloading the .zip from the `cdeterman ` source here, but installing again returns no error but also no installation feedback/information.

Any help is greatly appreciated. Also tried using `RPUD`, but none of their work seems to be able to function on Windows 10/Anaconda.

**Comment by cdeterman** [comment]
Hi @08walshth I don't have Windows 10 so I unfortunately can't try and reproduce this problem.  Have you tried opening an R session and installing with `install.packages('gpuR')`?  Also, I assume you already have an OpenCL SDK installed?

**Comment by 08walshth** [comment]
Hi Charles,

So I got the package installed again and I believe you had it right...my
OpenCL was expired/broken. Reinstalling OpenCL fixed it. But now...do you
have any examples or ideas of using gpuR for classification models, i.e.
neural nets, SVM, random forests? Thanks for the direct reply!

**Comment by cdeterman** [comment]
@08walshth I am glad you managed to get the package installed.  I will close this issue then.

Regarding your second question, unfortunately nothing yet for classification models.  Doing so requires much more involved work.  This package contains all the 'base' linear algebra functions to do many algorithms.  I am periodically working on implementing a neural network package that leverages `gpuR` and is inspired by keras/torch which you can find [here](https://github.com/cdeterman/prometheus).  Please note that the package is not functional at this time and requires a lot more work.

Regarding SVM and Random Forests, I need to do much more research to figure out how best to leverage GPUs for those algorithms.  It is my intent to implement these in my [gpuRml](https://github.com/gpuRcore/gpuRml) package but I have yet to even begin that.  I simply have not had the time to do so.  If you come across any good algorithms for these models that leverage GPUs feel free to send them to me or even feel free to attempt a contribution yourself.

**Comment by 08walshth** [comment]
Thanks Charles, I also JUST read the same on one of the other forums you're
on out there. Thanks for all your work in this area!
