### ISSUE TITLE
Install failure on Ubuntu 17.10

### ISSUE THREAD

**Issue by anadon** [cdeterman/gpuR#126]
Following the guide here: https://github.com/cdeterman/gpuR/wiki/Build-Instructions-for-Linux
I get the following truncated build failures (because so many lines are spit out I can't copy all of them): https://gist.github.com/anadon/9fc2950f2923d3aa9c470e2838e7f517

The result of clinfo is here: https://gist.github.com/anadon/0ca2ed263be379bb393ab1c17e77ed44

I'm not quite sure what I might be doing wrong, or what might actually be broken.

**Comment by anadon** [comment]
I've added the following packages: ocl-icd-opencl-dev ocl-icd-libopencl1 opencl-headers ocl-icd-dev ocl-icd-libopencl1 beignet clinfo 

I've also added myself to the 'video' group

Still massive number of warnings, but a new failure point: https://gist.github.com/anadon/757bef10a1c12e80dcad8ef80748672c

**Comment by anadon** [comment]
The Intel smoke tests have the following results: https://gist.github.com/anadon/c83d30cb1d065401ec6fc9a21d1a3120

**Comment by anadon** [comment]
Of possible interest is a darktable test: https://gist.github.com/anadon/efeb607359b13e49a88cc65e8f7dbaa6

**Comment by anadon** [comment]
Here are the available implementations on my system:
```
ls /etc/OpenCL/vendors
intel-beignet-x86_64-linux-gnu.icd  mesa.icd  pocl.icd
```

lspci: https://gist.github.com/anadon/8486744056b9c7d4f5b57abbd4c7669e
lscpu: https://gist.github.com/anadon/ea643bc1e2fb7087b2decb33c9bb1a72
complete installed package list: https://gist.github.com/6b026e17e12726f11d0e8b4d186ac5b1

**Comment by anadon** [comment]
Updated clinfo: https://gist.github.com/2d4f0dc4a030e329ba52d01cca128b79

**Comment by anadon** [comment]
What is the trouble with this difference?  From what I know, the differences between doubles and floats is automagically handled by the compiler.  Given that this would be for a research application where we do see differences in accuracy between doubles and floats, I am reluctant to use anything except doubles.

**Comment by cdeterman** [comment]
@anadon The difference is that your GPU simply doesn't support `double` precision.  If you require `double` for your research you need access to a device that supports it.  It doesn't matter how much 'magic' the compiler solves if the hardware cannot handle it.

**Comment by anadon** [comment]
I thought that got simulated in software.  In any case, it still isn't installing.  I can't get far enough to run that code on my laptop.  Got my desktop working on AMD stuff, but not so much with my laptop.

**Comment by cdeterman** [comment]
@anadon where is the install failing now?  That previous output I referenced could only have executed following a successful install of gpuR.

**Comment by anadon** [comment]
One moment, let me regenerate the logs.

**Comment by anadon** [comment]
Here: https://gist.github.com/7655d627e8a38845c16ec549482fc371
Though with easier text to read, it may be a viennaCL problem?  I'm not sure.  I'm typically more in classical algorithms and bioinformatics so this excursion has been burning me out.

**Comment by cdeterman** [comment]
@anadon I can understand the frustration with all the error warnings and I apologize for the install difficulties.  That said, there isn't an error in the file you linked.  It only contains warnings which, in themselves, prevent a successful build.  Are you sure you collected the entire output?  There should be a line which contains a g++ call on multiple `.o` and links to the libraries near the end.  That is typically where an error will happen just afterwards.  It should look something like the following:

```sh
g++ -std=gnu++11 -shared -L/usr/local/lib64 -o gpuR.so RcppExports.o chol.o context.o custom_math.o device.o gpuEigenPtr.o gpuMatrix_igemm.o norm.o platform.o set_row_order.o solve.o synchronize.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas2.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o -lOpenCL
```

**Comment by anadon** [comment]
Ah!  I see the problem now.  The logs are too long for gist and are being truncated.  Do you have a public email I can send these to?

**Comment by anadon** [comment]
Emailed.  Also, all R libraries are reported to be up to date.

**Comment by cdeterman** [comment]
@anadon I received your log file.  That is a strange error in which the install finds the devices and platforms but fails at load time.  Can you also try to install the current develop version?  I know I made some changes to the install that I want to make sure if this is a problem there as well.  You can install the develop version with the following R code.

```r
devtools::install_github('cdeterman/gpuR', ref = 'develop')
```

**Comment by anadon** [comment]
Are the new logs useful?

**Comment by cdeterman** [comment]
@anadon I understand you have a research project but I am also very busy with my day job and I cannot always attend to issues with gpuR.  I would love to spend all the time in the world working to make this package better and solve everyone's issues as they arise but I cannot.  Please be patient and I will do my best to try to help with your problem.  It is unlikely I will have time today.  It is more likely either tomorrow or Wednesday.

**Comment by anadon** [comment]
Sorry, I'm not trying to overwhelm.  I'm juggling a few projects right now, so balancing them can get tricky.

**Comment by anadon** [comment]
That file looks like `/etc/OpenCL/vendors/mesa.icd` is owned by `mesa-opencl-icd`, but it looks like it has been abandoned after the package was uninstalled.  After removing those, gpuR does work.
