### ISSUE TITLE
copying data from GPU to main RAM

### ISSUE THREAD

**Issue by AurelioG** [cdeterman/gpuR#128]
I installed gpuR and it works fine with K40 teslas nodes (each node, dual Xeon E5-2697v3 with dual K40), tutorial examples work fine by slurm scripts. My understanding was that any changes made in the GPU object (gpuMatrix) would be reflected in the core RAM object, because the gpuMatrix points to that object. If this is not the case, then how do I copy a matrix from the gpu back to core RAM? Many thanks
This is an example:
...
```r
filesNDVI <- list.files (pattern=".rst")
B <- as.matrix(raster(filesNDVI[21]))
B[1,1] ## here is printed a value between 0 and 10000
gpuB <- gpuMatrix(B)
gpuB <- gpuB/10000
gpuB[1,1] ## here is printed a value between 0 and 1, accordingly
B[1,1] ## here is printed a value between 0 and 10000, but I expected to be divided by 10000!! This was the original value
```

**Comment by cdeterman** [comment]
@AurelioG apologies for the delayed response.  I have been quite busy lately.  To clarify, are you expecting the values in `B` to be updated by the changes in `gpuB`?

**Comment by AurelioG** [comment]
Yes, values in B should be updated by the changes in gpuB.
 I would need the results for further processing or writing.
What would be your suggestion?
