### ISSUE TITLE
Error when kernel function calls another function

### ISSUE THREAD

**Issue by tamas-ferenci** [cdeterman/gpuR#129]
Consider the following - very silly, but illustrative - example:

     float sqrplusone( float in )
     {
       return in*in+1;
     }

     __kernel void SAXPY(__global float* x, __global float* y, float a)
     {
       const int i = get_global_id(0);
       y [i] += a * sqrplusone(x[i]);
     }

This is the content of `saxpy.cl`; let's now try to compile it:

      cl_args <- setup_opencl(objects = c("vclVector", "vclVector", "scalar"),
      intents = c("IN", "OUT", "IN"),
      queues = list("SAXPY", "SAXPY", "SAXPY"),
      kernel_maps = c("x", "y", "a"))
      custom_opencl("saxpy.cl", cl_args, "float")

This gives the following error message:

    Error in custom_opencl("saxpy.cl", cl_args, "float") : 
       Non OpenCL buffer kernel arguments don't match to initialized objects.

**Comment by cdeterman** [comment]
most recent commit resolves this issue
