### ISSUE TITLE
Installation failure with Centos 7.2

### ISSUE THREAD

**Issue by aapeters** [cdeterman/gpuR#136]
Hello
I can't wait to use gpuR, with it's capability to do GPU functions for R objects. Please help me solve the following installation problems.

I do not have roots access
The compilation node does not have a gpu on it.
OS: CentOS Linux release 7.2.1511 (Core)
R.3.3.0
R CMD INSTALL --configure-vars='OPENCL_INC=/usr/local/apps/cuda/cuda-9.1/include OPENCL_LIB64=/usr/local/apps/cuda/cuda-9.1/lib64 CUDA_HOME=/usr/local/apps/cuda/cuda-9.1' gpuR_2.0.0.tar.gz

It seems to find the OPENCL things ok:
OPENCL_FLAGS not set, using default -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS  -DCL_HPP_TARGET_OPENCL_VERSION=120
Linux OS
using CUDA_HOME
cl.hpp header exists
....

But then, when trying to compile the second thing:
g++ -std=c++11 -fPIC -std=c++11 -I/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/include    -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -fPIC -I'/usr/local/apps/cuda/cuda-9.1/include' -I/usr/local/apps/openssl/openssl-1.1.1/include -I/usr/local/apps/cuda/cuda-9.0/include/CL -I"/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/Rcpp/include" -I"/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RcppEigen/include" -I"/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include" -I"/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/BH/include"   -fpic  -g -O2 -c chol.cpp -o chol.o
In file included from /usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/scalar.hpp:29:0,
                 from /usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/tools/entry_proxy.hpp:27,
                 from /usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/detail/matrix_def.hpp:26,
                 from /usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/matrix.hpp:26,
                 from ../inst/include/gpuR/dynVCLMat.hpp:17,
                 from ../inst/include/gpuR/getVCLptr.hpp:5,
/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/meta/result_of.hpp: In instantiation of ‘struct viennacl::result_of::size_type<Eigen::CwiseUnaryView<Eigen::internal::scalar_real_ref_op<std::complex<float> >, Eigen::Matrix<std::complex<float>, -1, -1> > >’:
/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/traits/size.hpp:202:1:   required by substitution of ‘template<class MatrixType> typename viennacl::result_of::size_type<T>::type viennacl::traits::size2(const MatrixType&) [with MatrixType = Eigen::CwiseUnaryView<Eigen::internal::scalar_real_ref_op<std::complex<float> >, Eigen::Matrix<std::complex<float>, -1, -1> >]’
/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/matrix_proxy.hpp:443:3:   required from ‘void viennacl::copy(const CPUMatrixT&, viennacl::matrix_slice<viennacl::matrix<NumericT, viennacl::row_major, 1u> >&) [with CPUMatrixT = Eigen::CwiseUnaryView<Eigen::internal::scalar_real_ref_op<std::complex<float> >, Eigen::Matrix<std::complex<float>, -1, -1> >; NumericT = float]’
../inst/include/gpuR/dynVCLMat.hpp:344:44:   required from here
/usr/local/apps/R/em64t/R-3.3.0-intel2016-openmpi/lib64/R/library/RViennaCL/include/viennacl/meta/result_of.hpp:142:35: error: no type named ‘size_type’ in ‘class Eigen::CwiseUnaryView<Eigen::internal::scalar_real_ref_op<std::complex<float> >, Eigen::Matrix<std::complex<float>, -1, -1> >’
   typedef typename T::size_type   type;^M

Please help. Regards
Andrew Petersen

**Comment by cdeterman** [comment]
@aapeters I will try to spin up a docker image and try to reproduce.  In the mean time, could you try installing the `develop` version?  There have been many changes and I want to know if it still fails to compile there as well for you.  You can do so with `devtools::install_github('cdeterman/gpuR', ref = 'develop')`

**Comment by aapeters** [comment]
I figured it out! I could not try the devtools option because that depended on something which caused problems to install. But here is what worked:
For both R330 and R350, 
install.packages("assertive")
install.packages("RViennaOpenCL")
setting LD_LIBRARY_PATH and CUDA_HOME to point to the location of the libOpenCL.so file in the cuda package (cuda-9.1), needed for the last linking stage of the installation.
R CMD INSTALL --no-test-load gpuR_2.0.0.tar.gz
Alternatively, install.packages(gpuR) almost worked, except that I could not figure out how to --no-test-load with that process.

In R, after loading the library, on a gpu node, it works fine!

Thanks
AP

**Comment by cdeterman** [comment]
@aapeters glad you were able to resolve the issue.  Feel free to open another issue if you encounter other problems.
