### ISSUE TITLE
problem installing gpuR

### ISSUE THREAD

**Issue by csitaula** [cdeterman/gpuR#137]
Error:
> devtools::install_github('cdeterman/gpuR', ref = 'develop')
Downloading GitHub repo cdeterman/gpuR@develop
from URL https://api.github.com/repos/cdeterman/gpuR/zipball/develop
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing gpuR
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Chiru/AppData/Local/Temp/Rtmp21J5bI/devtools1260b983622/cdeterman-gpuR-e780286"  \
  --library="C:/Users/Chiru/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'gpuR' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'gpuR'
* removing 'C:/Users/Chiru/Documents/R/win-library/3.5/gpuR'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by cdeterman** [comment]
@csitaula as the install error states, you need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) in order to install `gpuR`.

**Comment by csitaula** [comment]
Worked!
