### ISSUE TITLE
modified dist method 

### ISSUE THREAD

**Issue by vsmaier** [cdeterman/gpuR#14]
I would like to request a second dist method. Something like

distance(A,B, method="euclidian").

Inputs are two sets of points and metric to use for the distance calculation. The idea is to compute the distance from every point in A to every point in B. So a modification from the existing method that computes all distances between all points in a set. 

Result would be a matrix containing A*B distance scores.

The scenario I am trying to solve is where I have a very large set of fixed points and need to test the distances of a secondary, variable set of points to the larger one. Hence I would also like to request a 'square euclidian' "metric" (I am aware this is not a proper mathematical metric) as this avoids computation of the square root and is therefore faster. This would still suffice to compare the squared distance against the squared value of a target/cutoff distance.
 
I am using OS X El Capitan and had no problems so far (well, SIP is a problem if you don't have a recovery partition but that is an Apple issue). Planning to also test the GPU selection under the other ticket. Using a Mac Pro with 2 GPUs so there is potential there. 

Thanks for all the great work.

**Comment by cdeterman** [comment]
Hi @vsmaier, thanks for submitting the issue.  Am I correct in assuming that the distances would calculated by comparing rows as done in the base `dist` function?  This is also the method provided in the [pdist package](https://cran.r-project.org/web/packages/pdist/pdist.pdf) which was written for pairwise distance calculations.

I think I will create an additional method distinct from `dist` (which was created for consistency with the `base` functions).  `distance` certainly seems like a logical choice.

The addition of a 'squared euclidean' distance should be simple.

I am happy to hear about another user with multiple GPUs. I look forward to hearing how it works for you.  I would really like to get it functional but I must work on enhancements like those through users like yourself until I have a second GPU myself.

**Comment by vsmaier** [comment]
The description in the pdist package actually sounds pretty much like what I was hoping for.

**Comment by cdeterman** [comment]
The `distance` function has been added.  You now can call

```r
gpuD <- distance(gpuA, gpuB, method = "euclidean")
```

'euclidean' is the default and can be omitted if desired.  The additional option of "sqEuclidean" is available for both `dist` and `distance` methods to get the 'squared' euclidean distance.
