### ISSUE TITLE
Installation Error on Windows 10 x64

### ISSUE THREAD

**Issue by chesun** [cdeterman/gpuR#150]
I followed the instructions but installation failed. Both NVIDIA CUDA SDK and Rtools were installed. Here's the console output:

> Sys.setenv(OPENCL_INC = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\include")
> Sys.setenv(OPENCL_LIB64 = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\lib\\x64")
> Sys.setenv(OPENCL_LIB32 = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\lib\\Win32")
> install.packages('gpuR')
Installing package into ‘C:/Users/sunch/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘gpuR’
installing the source package ‘gpuR’

trying URL 'https://cran.rstudio.com/src/contrib/gpuR_2.0.0.tar.gz'
Content type 'application/x-gzip' length 538276 bytes (525 KB)
downloaded 525 KB

* installing *source* package 'gpuR' ...
** package 'gpuR' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c chol.cpp -o chol.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c context.cpp -o context.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c custom_math.cpp -o custom_math.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c device.cpp -o device.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c gpuEigenPtr.cpp -o gpuEigenPtr.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c gpuMatrix_igemm.cpp -o gpuMatrix_igemm.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c norm.cpp -o norm.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c platform.cpp -o platform.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c set_row_order.cpp -o set_row_order.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c solve.cpp -o solve.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c synchronize.cpp -o synchronize.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c trunc_gpuMat.cpp -o trunc_gpuMat.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c utils-vcl.cpp -o utils-vcl.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vclPtr.cpp -o vclPtr.o
In file included from C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include/Eigen/Core:394:0,
                 from C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include/viennacl/meta/result_of.hpp:41,
                 from C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include/viennacl/scalar.hpp:29,
                 from C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include/viennacl/tools/entry_proxy.hpp:27,
                 from C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include/viennacl/detail/matrix_def.hpp:26,
                 from C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include/viennacl/matrix.hpp:26,
                 from ../inst/include/gpuR/dynVCLMat.hpp:17,
                 from vclPtr.cpp:4:
C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include/Eigen/src/Core/arch/SSE/Complex.h: In function 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = Eigen::internal::Packet2cf; typename Eigen::internal::unpacket_traits<Packet>::type = std::complex<float>]':
C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include/Eigen/src/Core/arch/SSE/Complex.h:103:50: warning: 'res.Eigen::internal::Packet2cf::v' is used uninitialized in this function [-Wuninitialized]
   res.v = _mm_loadl_pi(res.v, (const __m64*)&from);
                                                  ^
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas1.cpp -o vienna_blas1.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas2.cpp -o vienna_blas2.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas3.cpp -o vienna_blas3.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_eigen.cpp -o vienna_eigen.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_qr.cpp -o vienna_qr.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_stats.cpp -o vienna_stats.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -I"C:/Users/sunch/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/sunch/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_svd.cpp -o vienna_svd.o
cd ../inst/include/loader && /Rtools/bin/make ./x64/libOpenCL.a \
CC="C:/Rtools/mingw_64/bin/gcc " CFLAGS="    -O2 -Wall  -std=gnu99 -mtune=generic" AR="C:/Rtools/mingw_64/bin/ar" RM="rm -f" \
ICD_OS=icd_windows
make[1]: Entering directory '/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/inst/include/loader'
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd.c -o x64/icd.o
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd_dispatch.c -o x64/icd_dispatch.o
icd_dispatch.c: In function 'clGetExtensionFunctionAddressForPlatform':
icd_dispatch.c:1417:5: warning: 'clGetKernelSubGroupInfoKHR' is deprecated (declared at ../CL/cl_ext.h:330) [-Wdeprecated-declarations]
     CL_COMMON_EXTENSION_ENTRYPOINT_ADD(clGetKernelSubGroupInfoKHR);
     ^
icd_dispatch.c: In function 'clGetExtensionFunctionAddress':
icd_dispatch.c:1623:5: warning: 'clGetKernelSubGroupInfoKHR' is deprecated (declared at ../CL/cl_ext.h:330) [-Wdeprecated-declarations]
     CL_COMMON_EXTENSION_ENTRYPOINT_ADD(clGetKernelSubGroupInfoKHR);
     ^
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd_windows.c -o x64/icd_windows.o
rm -f x64/libOpenCL.a
C:/Rtools/mingw_64/bin/ar rcs x64/libOpenCL.a x64/icd.o x64/icd_dispatch.o x64/icd_windows.o
make[1]: Leaving directory '/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/inst/include/loader'
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o gpuR.dll tmp.def RcppExports.o chol.o context.o custom_math.o device.o gpuEigenPtr.o gpuMatrix_igemm.o norm.o platform.o set_row_order.o solve.o synchronize.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas2.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o -L../inst/include/loader/x64 -lOpenCL -LC:/PROGRA~1/R/R-35~1.2/bin/x64 -lR
installing to C:/Users/sunch/Documents/R/win-library/3.5/gpuR/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function for 'eigen' from package 'base' in package 'gpuR'
Creating a generic function for '%o%' from package 'base' in package 'gpuR'
Creating a generic function for 'nrow' from package 'base' in package 'gpuR'
Creating a generic function for 'ncol' from package 'base' in package 'gpuR'
Creating a generic function for 'crossprod' from package 'base' in package 'gpuR'
Creating a generic function for 'tcrossprod' from package 'base' in package 'gpuR'
Creating a generic function for 'cov' from package 'stats' in package 'gpuR'
Creating a generic function for 'colSums' from package 'base' in package 'gpuR'
Creating a generic function for 'rowSums' from package 'base' in package 'gpuR'
Creating a generic function for 'colMeans' from package 'base' in package 'gpuR'
Creating a generic function for 'rowMeans' from package 'base' in package 'gpuR'
Creating a generic function for 'dist' from package 'stats' in package 'gpuR'
Creating a generic function for 'diag' from package 'base' in package 'gpuR'
Creating a generic function for 'diag<-' from package 'base' in package 'gpuR'
Creating a generic function for 'det' from package 'base' in package 'gpuR'
Creating a generic function for 'norm' from package 'base' in package 'gpuR'
Creating a generic function for 'qr.R' from package 'base' in package 'gpuR'
Creating a generic function for 'qr.Q' from package 'base' in package 'gpuR'
Creating a generic function for 'typeof' from package 'base' in package 'gpuR'
Creating a generic function for 'colnames<-' from package 'base' in package 'gpuR'
** help
*** installing help indices
  converting help for package 'gpuR'
    finding HTML links ... done
    Arith-methods                           html  
    Compare-methods                         html  
    Math-methods                            html  
    Summary-methods                         html  
    as.gpuMatrix-methods                    html  
    as.gpuVector-methods                    html  
    as.vclVector-methods                    html  
    assert_has_double                       html  
    cgpuMatrix-class                        html  
    chol-methods                            html  
    colnames-methods                        html  
    cov-methods                             html  
    currentContext                          html  
    currentDevice                           html  
    currentPlatform                         html  
    custom_opencl                           html  
    cvclMatrix-class                        html  
    det-methods                             html  
    detectCPUs                              html  
    detectGPUs                              html  
    detectPlatforms                         html  
    deviceHasDouble                         html  
    deviceInfo                              html  
    deviceType                              html  
    dgpuMatrix-class                        html  
    dgpuVector-class                        html  
    diag-methods                            html  
    dim-methods                             html  
    dist-vclMatrix                          html  
    dvclMatrix-class                        html  
    dvclVector-class                        html  
    eigen-gpuMatrix                         html  
    extract-methods                         html  
    fgpuMatrix-class                        html  
    fgpuVector-class                        html  
    fvclMatrix-class                        html  
    fvclVector-class                        html  
    gpuMatrix-class                         html  
    gpuMatrix-crossprod                     html  
    gpuMatrix-methods                       html  
    gpuMatrix.colSums                       html  
    gpuR-block                              html  
    gpuR-deepcopy                           html  
    gpuR-package                            html  
    gpuR-slice                              html  
    gpuVector-class                         html  
    gpuVector-methods                       html  
    grapes-o-grapes-methods                 html  
    grapes-times-grapes-methods             html  
    has_cpu_skip                            html  
    has_double_skip                         html  
    has_gpu_skip                            html  
    has_multiple_double_skip                html  
    has_multiple_gpu_skip                   html  
    identity_matrix                         html  
    igpuMatrix-class                        html  
    igpuVector-class                        html  
    inplace-methods                         html  
    ivclMatrix-class                        html  
    ivclVector-class                        html  
    length-methods                          html  
    listContexts                            html  
    log-methods                             html  
    norm-methods                            html  
    nrow-gpuR                               html  
    permute-methods                         html  
    platformInfo                            html  
    pmax                                    html  
Rd warning: C:/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/man/pmax.Rd:21: file link 'pmax' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/man/pmax.Rd:21: file link 'pmin' in package 'base' does not exist and so has been treated as a topic
    pmin.vclVector                          html  
    pocl_check                              html  
    print.gpuMatrix                         html  
    qr-methods                              html  
    qr.R-methods                            html  
Rd warning: C:/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/man/qr.R-methods.Rd:26: file link 'qr.R' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/sunch/AppData/Local/Temp/RtmpcVV1XV/R.INSTALL1e82bd93904/gpuR/man/qr.R-methods.Rd:26: file link 'qr.Q' in package 'base' does not exist and so has been treated as a topic
    setContext                              html  
    set_device_context                      html  
    setup_opencl                            html  
    solve-methods                           html  
    svd-methods                             html  
    synchronize                             html  
    t-methods                               html  
    typeof-gpuR-methods                     html  
    vclMatrix-class                         html  
    vclMatrix-crossprod                     html  
    vclMatrix-methods                       html  
    vclMatrix.colSums                       html  
    vclVector-class                         html  
    vclVector-methods                       html  
    zgpuMatrix-class                        html  
    zvclMatrix-class                        html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for 'gpuR':
 .onAttach failed in attachNamespace() for 'gpuR', details:
  call: initContexts()
  error: ViennaCL: FATAL ERROR: ViennaCL encountered an unknown OpenCL error. Most likely your OpenCL SDK or driver is not installed properly. In some cases, this error is due to an invalid global work size or several kernel compilation errors.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net and supply at least the following information:
 * Operating System
 * Which OpenCL implementation (AMD, NVIDIA, etc.)
 * ViennaCL version
Many thanks in advance!
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/sunch/Documents/R/win-library/3.5/gpuR'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘gpuR’ had non-zero exit status

**Comment by cdeterman** [comment]
Have a look at the solution provided in issue #144, I have yet to right up an updated Wiki to include that information.

**Comment by chesun** [comment]
Thanks for the reply! Could you please elaborate on how to insert the file path in the windows registry editor?

**Comment by cdeterman** [comment]
@chesun I make a brief description how [here](https://github.com/cdeterman/gpuR/issues/144#issuecomment-454113922).  You can open up the registry editor by simply opening your windows search and finding `regedit.exe`.  The rest of the instructions in that issue should explain the rest.  You simply need to copy and paste the correct path in the new 'DWORD' that you create.

**Comment by chesun** [comment]
Thanks! I did that but the installation failed again and it gave me the exact same errors. Do I need to insert the Intel OpenCL path as well?

**Comment by cdeterman** [comment]
@chesun can you provide a screenshot of your windows registry?

**Comment by chesun** [comment]
![registry](https://user-images.githubusercontent.com/27652541/51702297-531f6f00-1fc8-11e9-9243-a0500d3dca93.PNG)

**Comment by cdeterman** [comment]
I can't see the full path, is that for the `nvopencl.dll` file?

**Comment by chesun** [comment]
Yes, that is the path to the nvopencl64.dll file. I’ll update the
screenshot and include the full path when I get back to my computer

**Comment by chesun** [comment]
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666
This is the full path I added to the registry. This was the location of the nvopencl64.dll as suggested by dualvim in issue #144

**Comment by chesun** [comment]
@cdeterman just wanted to follow up on this issue. Thank you!

**Comment by cdeterman** [comment]
@chesun sorry for my delay.  I assume you rebuilt after you added the path to the registry? @dualvim was there anything else you did after adding that path to the Vendors registry?

**Comment by chesun** [comment]
I’m assuming by rebuilding you meant reinstalling the package? If so then
yes and it still didn’t work.

**Comment by dualvim** [comment]
Absolutely nothing more, @cdeterman . I had built the gpuR package some days before I try what I said. 

@chesun, did you check carefully the file directory before copying to the registry? Because if you mistakenly copy the wrong path, when you try to load the gpuR package, the R freezes. 

I suggest to check careffuly the right folder in `C:\Windows\System32\` where the `nvopencl64.dll` file is.

In my  `C:\Windows\System32\` this file is in 47 folders (!) so I recommend to look for the most recent one.

**Comment by dualvim** [comment]
Just a screenshot of a search that I did right now for the `nvopencl64.dll` file:
![image](https://user-images.githubusercontent.com/7637348/52424861-fcdf1f80-2ae1-11e9-8ee9-71052abf66b3.png)


You must copy the file of the most recent one, like the one I selected in the image above.

**Comment by cdeterman** [comment]
@chesun did the information from dualvim help?  This seems to be a 'solved' problem that is a consequence of how NVIDIA installs on Windows 10 given their bias away from OpenCL.  If not, I'm not sure how else to direct you, possibly your installation isn't correct in some way but I could only guess.

**Comment by dualvim** [comment]
I think that it's solved. Just a remainder here: Everytime that you update the "GeForce Game Ready Driver", you must repeat the procedure that I explained here and in the other post. I figured this out today when I tried to use the `gpuR` and it didn't find my GeForce device, then, I just had to update the folder in RegEdit and everything is working fine here.

I don't know why NVIDIA is making difficult to use the OpenCL resources. I used the `gpuR` in may and June and I never had this problem. It appeared when I tried to use in November and posted the issue here. Fortunatelly I think that this bypass will work for a long time! Thank you very much for the great R package @cdeterman!

**Comment by cdeterman** [comment]
I will close this issue then until such a time that it appears there is a different problem with Windows 10 OpenCL with NVIDIA.  Thanks to all involved.

**Comment by anwilk** [comment]
@chesun I was having the same issue. However, once you point the registry to the DLL file _itself_ (eg. C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666\nvopencl64.dll) then it recognizes! Pointing just to the file it is contained within is not enough and this is my guess as to what is wrong
