### ISSUE TITLE
gpuR Windows 10 (w. admin rights) - Lazy loading failed -- error.. unused arguments

### ISSUE THREAD

**Issue by zekeargus** [cdeterman/gpuR#154]
Hello. Followed instructions in "Build Instructions for Windows"
https://github.com/cdeterman/gpuR/wiki/Build-Instructions-for-Windows

installed NVIDIA SDKs, set environmental variables globally within R
Sys.setenv(OPENCL_INC = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include")
Sys.setenv(OPENCL_LIB32 = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/Win32")
Sys.setenv(OPENCL_LIB64 = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64")

install.packages('gpuR')

Error I get is:
Error in match.call(definition, call, expand.dots, envir) : 
  unused arguments (na.rm = c("missing", ""), dims = c("missing", ""))
Error: unable to load R code in package 'gpuR'
Execution halted
ERROR: lazy loading failed for package 'gpuR'
* removing 'C:/Program Files/R/R-3.6.0/library/gpuR'
Warning in install.packages :
  installation of package ‘gpuR’ had non-zero exit status

Machine (laptop):
Windows 10 (Enterprise 64-bit) w. NVIDIA Quadro M620
R version 3.6.0 (2019-04-26)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

NVIDIA CUDA 10.1.104 driver

**Comment by cdeterman** [comment]
Please see issue #152.  I am trying to get the fix for R 3.6 pushed to CRAN.  You can install by pulling from this git repo with `devtools::install_github('cdeterman/gpuR')`
