### ISSUE TITLE
gpuR pulled from CRAN due to unresolved check errors

### ISSUE THREAD

**Issue by jeffkeller87** [cdeterman/gpuR#155]
Visiting the [`gpurR` CRAN page](https://cran.r-project.org/web/packages/gpuR/) shows this message:

```
Package ‘gpuR’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-05-12 as check problems were not corrected despite reminders. 
```

**Comment by cdeterman** [comment]
Yes, I am dealing with some frustrations with R-devel during the CRAN submission.  I need to resolve why the `BH` package doesn't have certain files.  Hopefully I will get it back up on CRAN soon.

**Comment by cdeterman** [comment]
This has been resolved now, see [here](https://cran.r-project.org/web/packages/gpuR/index.html)
