### ISSUE TITLE
gpuR recognizes Intel Graphic card but not nvidia

### ISSUE THREAD

**Issue by martinguerrero89** [cdeterman/gpuR#160]
Hi!
Thank you for your great package, I've used it in a Linux environment and works perfectly
I was trying to set it up in my windows machine but I cannot make gpuR "see" my nvidia card
Below the code used for installation and the output:

#Already installed CUDA toolkit v10.1 properly

Sys.setenv(OPENCL_INC = "/path/to/opencl/headers/")
Sys.setenv(OPENCL_LIB32 = "/path/to/opencl/library/x86")
Sys.setenv(OPENCL_LIB64 = "/path/to/opencl/library/x86_64")

Sys.setenv(OPENCL_INC   = "C:\\Intel\\OpenCL\\sdk\\include\\CL")
Sys.setenv(OPENCL_LIB32 = "C:\\Intel\\OpenCL\\sdk\\lib\\x86")
Sys.setenv(OPENCL_LIB64 = "C:\\Intel\\OpenCL\\sdk\\lib\\x64")

Sys.setenv(OPENCL_LIB64 = "C:/Archivos de programa/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64")
Sys.setenv(OPENCL_INC = "C:/Archivos de programa/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include/CL")
Sys.setenv(CUDA_HOME="C:/Archivos de programa/NVIDIA GPU Computing Toolkit/CUDA/v10.1")

install_github("cdeterman/gpuR", ref = "develop")

Downloading GitHub repo cdeterman/gpuR@develop
These packages have more recent versions available.
Which would you like to update?

1:   All
2:   CRAN packages only
3:   None
4:   RViennaCL (1.7.1.7 -> 1.7.1.8) [CRAN]
5:   xfun      (0.7     -> 0.8    ) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
RViennaCL (1.7.1.7 -> 1.7.1.8) [CRAN]
xfun      (0.7     -> 0.8    ) [CRAN]
Installing 2 packages: RViennaCL, xfun
Installing packages into ‘C:/Users/Usuario/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/RViennaCL_1.7.1.8.zip'
Content type 'application/zip' length 774884 bytes (756 KB)
downloaded 756 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/xfun_0.8.zip'
Content type 'application/zip' length 171861 bytes (167 KB)
downloaded 167 KB

package ‘RViennaCL’ successfully unpacked and MD5 sums checked
package ‘xfun’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Usuario\AppData\Local\Temp\Rtmp4MufYK\downloaded_packages
√  checking for file 'C:\Users\Usuario\AppData\Local\Temp\Rtmp4MufYK\remotes1d7428b52218\cdeterman-gpuR-6799d7f/DESCRIPTION' ... 
-  preparing 'gpuR': (461ms)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  running 'cleanup.win' (495ms)
-  checking for LF line-endings in source and make files and shell scripts (707ms)
-  checking for empty or unneeded directories
-  building 'gpuR_2.0.3.tar.gz'
   Warning: file 'gpuR/cleanup' did not have execute permissions: corrected
   Warning: file 'gpuR/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/Usuario/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'gpuR' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c chol.cpp -o chol.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c context.cpp -o context.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c custom_math.cpp -o custom_math.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c device.cpp -o device.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c gpuEigenPtr.cpp -o gpuEigenPtr.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c gpuMatrix_igemm.cpp -o gpuMatrix_igemm.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c norm.cpp -o norm.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c platform.cpp -o platform.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c set_row_order.cpp -o set_row_order.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c solve.cpp -o solve.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c synchronize.cpp -o synchronize.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c trunc_gpuMat.cpp -o trunc_gpuMat.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c utils-vcl.cpp -o utils-vcl.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vclPtr.cpp -o vclPtr.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas1.cpp -o vienna_blas1.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas2.cpp -o vienna_blas2.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_blas3.cpp -o vienna_blas3.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_eigen.cpp -o vienna_eigen.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_qr.cpp -o vienna_qr.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_stats.cpp -o vienna_stats.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -UNDEBUG -I"C:/Users/Usuario/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/RViennaCL/include" -I"C:/Users/Usuario/Documents/R/win-library/3.5/BH/include"        -O2 -Wall  -mtune=generic -c vienna_svd.cpp -o vienna_svd.o
cd ../inst/include/loader && mkdir -p ./x64 && /Rtools/bin/make ./x64/libOpenCL.a \
CC="C:/Rtools/mingw_64/bin/gcc " CFLAGS="    -O2 -Wall  -std=gnu99 -mtune=generic" AR="C:/Rtools/mingw_64/bin/ar" RM="rm -f" \
ICD_OS=icd_windows
make[1]: Entering directory '/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/inst/include/loader'
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd.c -o x64/icd.o
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd_dispatch.c -o x64/icd_dispatch.o
icd_dispatch.c: In function 'clGetExtensionFunctionAddressForPlatform':
icd_dispatch.c:1417:5: warning: 'clGetKernelSubGroupInfoKHR' is deprecated (declared at ../CL/cl_ext.h:330) [-Wdeprecated-declarations]
     CL_COMMON_EXTENSION_ENTRYPOINT_ADD(clGetKernelSubGroupInfoKHR);
     ^
icd_dispatch.c: In function 'clGetExtensionFunctionAddress':
icd_dispatch.c:1623:5: warning: 'clGetKernelSubGroupInfoKHR' is deprecated (declared at ../CL/cl_ext.h:330) [-Wdeprecated-declarations]
     CL_COMMON_EXTENSION_ENTRYPOINT_ADD(clGetKernelSubGroupInfoKHR);
     ^
C:/Rtools/mingw_64/bin/gcc  -I../ -O2 -Wall  -std=gnu99 -mtune=generic -c icd_windows.c -o x64/icd_windows.o
rm -f x64/libOpenCL.a
C:/Rtools/mingw_64/bin/ar rcs x64/libOpenCL.a x64/icd.o x64/icd_dispatch.o x64/icd_windows.o
make[1]: Leaving directory '/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/inst/include/loader'
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o gpuR.dll tmp.def RcppExports.o chol.o context.o custom_math.o device.o gpuEigenPtr.o gpuMatrix_igemm.o norm.o platform.o set_row_order.o solve.o synchronize.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas2.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o -L../inst/include/loader/x64 -lOpenCL -LC:/PROGRA~1/R/R-35~1.2/bin/x64 -lR
installing to C:/Users/Usuario/Documents/R/win-library/3.5/gpuR/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function for 'eigen' from package 'base' in package 'gpuR'
Creating a generic function for '%o%' from package 'base' in package 'gpuR'
Creating a generic function for 'tcrossprod' from package 'base' in package 'gpuR'
Creating a generic function for 'nrow' from package 'base' in package 'gpuR'
Creating a generic function for 'ncol' from package 'base' in package 'gpuR'
Creating a generic function for 'crossprod' from package 'base' in package 'gpuR'
Creating a generic function for 'cov' from package 'stats' in package 'gpuR'
Creating a generic function for 'colSums' from package 'base' in package 'gpuR'
Creating a generic function for 'rowSums' from package 'base' in package 'gpuR'
Creating a generic function for 'colMeans' from package 'base' in package 'gpuR'
Creating a generic function for 'rowMeans' from package 'base' in package 'gpuR'
Creating a generic function for 'dist' from package 'stats' in package 'gpuR'
Creating a generic function for 'diag' from package 'base' in package 'gpuR'
Creating a generic function for 'diag<-' from package 'base' in package 'gpuR'
Creating a generic function for 'det' from package 'base' in package 'gpuR'
Creating a generic function for 'norm' from package 'base' in package 'gpuR'
Creating a generic function for 'qr.R' from package 'base' in package 'gpuR'
Creating a generic function for 'qr.Q' from package 'base' in package 'gpuR'
Creating a generic function for 'typeof' from package 'base' in package 'gpuR'
Creating a generic function for 'colnames<-' from package 'base' in package 'gpuR'
** help
*** installing help indices
  converting help for package 'gpuR'
    finding HTML links ... done
    Arith-methods                           html  
    Compare-methods                         html  
    Math-methods                            html  
    Summary-methods                         html  
    as.gpuMatrix-methods                    html  
    as.gpuVector-methods                    html  
    as.vclVector-methods                    html  
    assert_has_double                       html  
    cgpuMatrix-class                        html  
    chol-methods                            html  
    colnames-methods                        html  
    cov-methods                             html  
    currentContext                          html  
    currentDevice                           html  
    currentPlatform                         html  
    custom_opencl                           html  
    cvclMatrix-class                        html  
    det-methods                             html  
    detectCPUs                              html  
    detectGPUs                              html  
    detectPlatforms                         html  
    deviceHasDouble                         html  
    deviceInfo                              html  
    deviceType                              html  
    dgpuMatrix-class                        html  
    dgpuVector-class                        html  
    diag-methods                            html  
    dim-methods                             html  
    dist-vclMatrix                          html  
    dvclMatrix-class                        html  
    dvclVector-class                        html  
    eigen-gpuMatrix                         html  
    extract-methods                         html  
    fgpuMatrix-class                        html  
    fgpuVector-class                        html  
    fvclMatrix-class                        html  
    fvclVector-class                        html  
    gpuMatrix-class                         html  
    gpuMatrix-crossprod                     html  
    gpuMatrix-methods                       html  
    gpuMatrix.colSums                       html  
    gpuR-block                              html  
    gpuR-deepcopy                           html  
    gpuR-package                            html  
    gpuR-slice                              html  
    gpuVector-class                         html  
    gpuVector-methods                       html  
    grapes-o-grapes-methods                 html  
    grapes-times-grapes-methods             html  
    has_cpu_skip                            html  
    has_double_skip                         html  
    has_gpu_skip                            html  
    has_multiple_double_skip                html  
    has_multiple_gpu_skip                   html  
    identity_matrix                         html  
    igpuMatrix-class                        html  
    igpuVector-class                        html  
    inplace-methods                         html  
    ivclMatrix-class                        html  
    ivclVector-class                        html  
    length-methods                          html  
    listContexts                            html  
    log-methods                             html  
    norm-methods                            html  
    nrow-gpuR                               html  
    permute-methods                         html  
    platformInfo                            html  
    pmax                                    html  
Rd warning: C:/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/man/pmax.Rd:21: file link 'pmax' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/man/pmax.Rd:21: file link 'pmin' in package 'base' does not exist and so has been treated as a topic
    pmin.vclVector                          html  
    pocl_check                              html  
    print.gpuMatrix                         html  
    qr-methods                              html  
    qr.R-methods                            html  
Rd warning: C:/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/man/qr.R-methods.Rd:26: file link 'qr.R' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/Usuario/AppData/Local/Temp/RtmpwZVbV2/R.INSTALL25d412aa30f8/gpuR/man/qr.R-methods.Rd:26: file link 'qr.Q' in package 'base' does not exist and so has been treated as a topic
    setContext                              html  
    set_device_context                      html  
    setup_opencl                            html  
    solve-methods                           html  
    svd-methods                             html  
    synchronize                             html  
    t-methods                               html  
    typeof-gpuR-methods                     html  
    vclMatrix-class                         html  
    vclMatrix-crossprod                     html  
    vclMatrix-methods                       html  
    vclMatrix.colSums                       html  
    vclVector-class                         html  
    vclVector-methods                       html  
    zgpuMatrix-class                        html  
    zvclMatrix-class                        html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
Number of platforms: 1
- platform: Intel(R) Corporation: OpenCL 2.0 
  - context device index: 0
    - Intel(R) HD Graphics 530
  - context device index: 1
    - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
checked all devices
completed initialization
* DONE (gpuR)
In R CMD INSTALL

#And then: 

library(gpuR)
Number of platforms: 1
- platform: Intel(R) Corporation: OpenCL 2.0 
  - context device index: 0
    - Intel(R) HD Graphics 530
  - context device index: 1
    - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
checked all devices
completed initialization

Any help on how to make my nvidia GPU work properly in gpuR???

Thank you very much for your help

**Comment by xiaoluolorn** [comment]
I have the same situation as you, have you worked it out?

**Comment by martinguerrero89** [comment]
Mmm not, I kept trying but no solution and Charles hasn´t answered yet. I decided to go back to my linux partition but this is not a good solution...
If you get it working please let me know!

**Comment by andrewkurzweil** [comment]
Have you tried the solution offered here: https://github.com/cdeterman/gpuR/issues/144#issuecomment-455431253

**Comment by martinguerrero89** [comment]
@andrewkurzweil  thanks for pointing me to that thread, I did not see it. After I try it I'll get the thread closed

**Comment by martinguerrero89** [comment]
It did work! thanks @andrewkurzweil  !
