### ISSUE TITLE
Error in gpuR install

### ISSUE THREAD

**Issue by rodrigosantana** [cdeterman/gpuR#28]
I am trying to install gpuR but I am not having sucess.
I installed the requisites, opencl-headers, cuda and the dependencies R packages, but the gpuR installation returns "version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference".

How could I solve this problem?

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by cdeterman** [comment]
Hello @rodrigosantana, it seems the OPENCL headers are too new for CUDA OPENCL version.  I have been trying to make this installation smoother with the next version.  Could you please try installing directly from the development version on my github with the following command:

    devtools::install_github('cdeterman/gpuR', ref = 'develop')

**Comment by rodrigosantana** [comment]
Hi @cdeterman, its me again. Thank you for the answer. 

Well, unfortunatelly the problem persists. 

symbol clCreateCommandQueueWithProperties, version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference

Its possible to use another CUDA libraries? Maybe, OPENGL or something?

**Comment by cdeterman** [comment]
@rodrigosantana, would you be able to provide some, if not all, of the compilation output?  You can put it all either here or in a link to pastebin.

Thanks

**Comment by rodrigosantana** [comment]
@cdeterman 

part 1 - http://pastebin.com/d0ccxbiS
part 2 - http://pastebin.com/0SCEpr3v
part 3 - http://pastebin.com/feCykbpa

**Comment by cdeterman** [comment]
@rodrigosantana AH!  It appears your `CUDA_HOME` is not set.  I thought this would normally be set by default when you install CUDA but I guess not.  You can either set it either in your `.bashrc` file so it is set globally or with `Sys.setenv` in RStudio/R.  

A link that demonstrates setting `CUDA_HOME` is [here](http://www.r-tutor.com/gpu-computing/cuda-installation/cuda7.5-ubuntu).  Either way, the variable likely will point to something like `/usr/local/cuda-x.y` on a Ubuntu system.

**Comment by cdeterman** [comment]
@rodrigosantana Did you ever manage to get `gpuR` installed or are you still having problems?  I would like to close this issue if you have successfully installed it.

**Comment by rodrigosantana** [comment]
@cdeterman Unfortunatelly, I still having problems. I setted the CUDA_HOME as you recommended but the same issue persists. I really don't know how to fix that.

**Comment by cdeterman** [comment]
@rodrigosantana are you able to see the CUDA_HOME environmental variable within R with `Sys.getenv('CUDA_HOME')`?  Also, please provide the output from the install again.  I don't need everything but the first few lines and a few compiler statements (those with g++ at the front) and the last lines are the most helpful.  Thanks

**Comment by rodrigosantana** [comment]
@cdeterman 
> Sys.getenv('CUDA_HOME')
[1] "/opt/cuda"

I remove cuda and install again and after that I set the CUDA_HOME in baserc and in R with Sys.setenv.
Now the issue is fixed. But, if we set the CUDA_HOME in bashrc file is this not set globally? Why it was necessary to set again with Sys.setenv in R?

**Comment by cdeterman** [comment]
@rodrigosantana Are you using R from the command line or Rstudio?

**Comment by cdeterman** [comment]
@rodrigosantana if from the commandline you shouldn't need to set the enviornmental variable.  If using Rstudio it has its' own initialization scheme that may omit environmental variables.
