### ISSUE TITLE
Including source of OpenCL ICD loader in package?

### ISSUE THREAD

**Issue by yixuan** [cdeterman/gpuR#31]
Hi Charles, recently I did some experiments with OpenCL and it seems that `OpenCL.dll` or `OpenCL.so` can be easily compiled from the [OpenCL ICD loader source](https://github.com/KhronosGroup/OpenCL-ICD-Loader). So I think that we could just include them in the package, so that users do not even need to install any giant-sized OpenCL SDK. All they need is the OpenCL runtime library, which is usually already included in the video card driver.

This also allows the Windows and Mac binary package to be available on CRAN, and it will be much more convenient for users to try things out without stepping into the troublesome installation part.

How do you think of this idea? If it makes any sense, I'd like to do some work on that. :smile:

**Comment by cdeterman** [comment]
Sure, we can definitely create a branch and begin experimenting with that.  It would be nice to avoid a lot of the headaches with the SDK installations.  

However, I will ultimately need to confirm that this is okay with the CRAN community.  Generally speaking it is frowned upon to distribute any .so or .dll files.  It is usually recommended to provide all the source code and compile it all during installation.  Furthermore, R packages are notoriously difficult to get mutliple .so files to play nice together (I don't think I have ever found a package that accomplishes this).  

The idea is definitely good and worth pursuing but I expect we will likely find more difficulties (always happy to be proven wrong here).

**Comment by yixuan** [comment]
I guess we can compile the ICD loader statically into the package dll/so -- `OpenCL.dll/so` is basically a dispatcher of OpenCL implementations, so it is similar to any other

**Comment by yixuan** [comment]
I tried [a minimal example](https://github.com/yixuan/miniGPU) and it seems to work, except for the build of a Windows 32-bit version in my own machine. In that case the linker says

```
undefined reference to `InitOnceExecuteOnce'
```

It looks more like a compiler toolchain problem, since the same code can be compiled successfully for 64-bit version.

**Comment by yixuan** [comment]
The issue on 32-bit Windows has been solved, so this method should be applicable on all major platforms of R. Later I will create a branch for `gpuR`.

**Comment by cdeterman** [comment]
This appears to be working quite well right now.  I am switching between windows systems and linux boxes periodically on my end and a few OSX users are having success.  I am reaching a point to consider this issue resolved.  Any additional thoughts @yixuan ?

**Comment by yixuan** [comment]
Glad to hear that. I'll close this.
