### ISSUE TITLE
Installation of "develop" branch on OS X

### ISSUE THREAD

**Issue by dselivanov** [cdeterman/gpuR#38]
Thank you a lot for this package and all the work done. I have issue with installation of "develop" branch on OS X.
I have pretty [modern macbook](https://support.apple.com/kb/SP719?locale=ru_RU&viewlocale=en_US) with Intel Iris Pro graphics and openCl 1.2 - 
I can package from install master branch, however "develop" branch produces:
>  .........
cd ../inst/include/loader/ && make libOpenCL.a \
	CC="clang" CFLAGS="  -fPIC  -Wall -mtune=core2 -g -O2  -march=native -ffast-math -Ofast -mtune=native" AR="ar" RM="rm -f" \
	ICD_OS=icd_linux
clang -I../ -fPIC  -Wall -mtune=core2 -g -O2  -march=native -ffast-math -Ofast -mtune=native -c icd.c -o icd.o
In file included from icd.c:40:
In file included from ./icd.h:53:
../CL/cl.h:703:74: error: expected function body after function declarator
  ...cl_command_queue     /* command_queue */) CL_API_SUFFIX__VERSION_2_1;
                                               ^
../CL/cl.h:708:63: error: expected function body after function declarator
                        cl_ulong*       /* host_timestamp */) CL_API_SUF...
                                                              ^
../CL/cl.h:712:52: error: expected function body after function declarator
               cl_ulong *   /* host_timestamp */)  CL_API_SUFFIX__VERSION_2_1;
                                                   ^
../CL/cl.h:749:80: error: expected function body after function declarator
  ...cl_int *                 /* errcode_ret */) CL_API_SUFFIX__VERSION_2_0;
                                                 ^
../CL/cl.h:793:60: error: expected function body after function declarator
             cl_int *                   /* errcode_ret */) CL_API_SUFFIX...
                                                           ^
../CL/cl.h:828:60: error: expected function body after function declarator
              size_t *         /* param_value_size_ret */) CL_API_SUFFIX...
                                                           ^
../CL/cl.h:841:46: error: expected function body after function declarator
           cl_uint          /* alignment */) CL_API_SUFFIX__VERSION_2_0;
                                             ^
../CL/cl.h:845:48: error: expected function body after function declarator
          void *            /* svm_pointer */) CL_API_SUFFIX__VERSION_2_0;
                                               ^
../CL/cl.h:851:81: error: expected function body after function declarator
  ...cl_int *                       /* errcode_ret */) CL_API_SUFFIX__VERSION...
                                                       ^
../CL/cl.h:894:56: error: expected function body after function declarator
                     cl_int*        /* errcode_ret */) CL_API_SUFFIX__VE...
                                                       ^
../CL/cl.h:966:48: error: expected function body after function declarator
              cl_int*       /* errcode_ret */) CL_API_SUFFIX__VERSION_2_1;
                                               ^
../CL/cl.h:983:56: error: expected function body after function declarator
                         const void * /* arg_value */) CL_API_SUFFIX__VE...
                                                       ^
../CL/cl.h:989:61: error: expected function body after function declarator
                    const void *         /* param_value */) CL_API_SUFFI...
                                                            ^
../CL/cl.h:1022:82: error: expected function body after function declarator
  ...size_t*                     /* param_value_size_ret */ ) CL_API_SUFFIX__...
                                                              ^
../CL/cl.h:1322:49: error: expected function body after function declarator
                 cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
                                                ^
../CL/cl.h:1332:51: error: expected function body after function declarator
                   cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
                                                  ^
../CL/cl.h:1342:52: error: expected function body after function declarator
                    cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
                                                   ^
../CL/cl.h:1352:48: error: expected function body after function declarator
                cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
                                               ^
../CL/cl.h:1359:50: error: expected function body after function declarator
                  cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [icd.o] Error 1
make: *** [../inst/include/loader/libOpenCL.a] Error 2
ERROR: compilation failed for package ‘gpuR’
* removing ‘/Users/dymitriyselivanov/Library/R/3.3/library/gpuR’
Error: Command failed (1)

**Comment by cdeterman** [comment]
Ah, a consequence of our recent work to avoid needing users to install an OpenCL SDK.  I don't think this should ever be necessary for OSX systems.  I have updated the `configure` file.  Please try the install once more from the `develop` branch.

**Comment by dselivanov** [comment]
Also for master branch:
```r
library(gpuR)
A <- seq.int(from=0, to=999)
gpuA <- gpuVector(A)
```
> Error in deviceHasDouble(platform_index, device_index) : 
  is_integer : gpu_idx is not of type 'integer'; it has class 'numeric'.

Seems somewhere internally  we call `deviceHasDouble` with numeric argument. I can open new issue for that.

```r
gpuInfo()
```
> $deviceName
[1] "Iris Pro"
$deviceVendor
[1] "Intel"
$numberOfCores
[1] 40
$maxWorkGroupSize
[1] 512
$maxWorkItemDim
[1] 3
$maxWorkItemSizes
[1] 512 512 512
$deviceMemory
[1] 1610612736
$clockFreq
[1] 1200
$localMem
[1] 65536
$maxAllocatableMem
[1] 402653184
$available
[1] "yes"
$deviceExtensions
 [1] "cl_APPLE_SetMemObjectDestructor"      "cl_APPLE_ContextLoggingFunctions"    
 [3] "cl_APPLE_clut"                        "cl_APPLE_query_kernel_names"         
 [5] "cl_APPLE_gl_sharing"                  "cl_khr_gl_event"                     
 [7] "cl_khr_global_int32_base_atomics"     "cl_khr_global_int32_extended_atomics"
 [9] "cl_khr_local_int32_base_atomics"      "cl_khr_local_int32_extended_atomics" 
[11] "cl_khr_byte_addressable_store"        "cl_khr_image2d_from_buffer"          
[13] "cl_khr_gl_depth_images"               "cl_khr_depth_images"                 
[15] "cl_khr_3d_image_writes"               ""                                    
$double_support
[1] FALSE

**Comment by cdeterman** [comment]
@dselivanov Did the recent change to the `configure` fix the `develop` install?  I would hold off on any issue until you can confirm it is an issue in the `develop` branch.

**Comment by dselivanov** [comment]
Thanks for quick fix! works now.

**Comment by dselivanov** [comment]
@cdeterman yes, latest commit to `develop` fixed the problem.
