### ISSUE TITLE
Problem with install of gpuR on Mac Pro trashcan AMD Firepro 500s

### ISSUE THREAD

**Issue by clmgit** [cdeterman/gpuR#42]
Tried and failed.  errors in attached file.  i installed the C++11 headers for opencl as instructed.  it looks like clang is set for C++11.  i have os 10.11.6 (not Sierra).  I assume the sdk for the graphics cards are shipped with the mac.
[error_install_gpuR_macpro_amdfirepro500.zip](https://github.com/cdeterman/gpuR/files/504951/error_install_gpuR_macpro_amdfirepro500.zip)

**Comment by cdeterman** [comment]
Please try installing the current `develop` version with:

```r
devtools::install_github('cdeterman/gpuR', ref = 'develop')
```

**Comment by clmgit** [comment]
tried the dev version, no go.  file attached.  i needed to also move to the dev version of RViennaCL.  The first issue in the attached file occurs early with "clang: warning: -framework OpenCL: 'linker' input unused" warning.

thanks for the effort on this, it will be great for the mac users if it can work.
[error gpuR trial oct 3 2016 mac pro.txt.zip](https://github.com/cdeterman/gpuR/files/506408/error.gpuR.trial.oct.3.2016.mac.pro.txt.zip)

---Chuck

**Comment by cdeterman** [comment]
Bah... I keep forgetting to tell users with the 'develop' version they also need the RViennaCL from my github too.  

```r
devtools::install_github('cdeterman/RViennaCL')
```

That should get you what you need.  I know multiple mac users are successfully using the package so it should work for you.

**Comment by dselivanov** [comment]
For me all works very smoothly. Can't imagine how much effort was made to
make it work out of the box. Really impressed.

3 окт. 2016 г. 6:12 ПП пользователь "Charles Determan" <
notifications@github.com> написал:

Bah... I keep forgetting to tell users with the 'develop' version they also
need the RViennaCL from my github too.

devtools::install_github('cdeterman/RViennaCL')

That should get you what you need. I know multiple mac users are
successfully using the package so it should work for you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cdeterman/gpuR/issues/42#issuecomment-251116183>, or mute
the thread

**Comment by clmgit** [comment]
not to worry, i caught that.  but still no joy, output file on github.  we mac users really appreciate your efforts.

**Comment by clmgit** [comment]
i am on a trashcan mac pro with two firepro gpus.  it is possible that these are touchier than other apple products.

**Comment by cdeterman** [comment]
@clmgit it shouldn't be a problem.   I have seen other users with multiple firepro gpus.  Do you have the most recent installation output again?

**Comment by clmgit** [comment]
yes on github.  also attached to this email. —c.

**Comment by cdeterman** [comment]
@clmgit I think you need to attach it manually on github.  There is no attachment in my email or on the github issue.

**Comment by clmgit** [comment]
ok here is a manual upload
[error_gpuR_Part2.txt.zip](https://github.com/cdeterman/gpuR/files/506452/error_gpuR_Part2.txt.zip)

**Comment by cdeterman** [comment]
@clmgit okay, please try once more.  I have updated my macosx branch and it is currently building without a problem.

**Comment by clmgit** [comment]
still an issue.  the first clang warning is gone (clang: warning: -framework OpenCL: 'linker' input unused) but the remaining issues seem similar. ---best, chuck
[error_gpuR_Part3.zip](https://github.com/cdeterman/gpuR/files/506820/error_gpuR_Part3.zip)

**Comment by cdeterman** [comment]
Hmm... what version of clang++ do you have?  Also, what version of RcppEigen do you have installed?  It seems to be having issues with the Eigen library from the build output is my guess at the moment.

Also, @dselivanov what version is your Mac?  I am curious if this is a versioning problem.

**Comment by dselivanov** [comment]
I'm on latest sierra os.

**Comment by cdeterman** [comment]
Okay, I actually doubt the osx version problem now that I check the Travis CI platform.  It is running os 10.9.6 by default so an even older system thatn @clmgit.  I should be able to change the version to 10.11 by setting `osx_image`.  I will give it a go and see if El Capitan's more recent version is causing the problem.

**Comment by cdeterman** [comment]
@clmgit I am having troubles with the newer El Capitan version.  I can't seem to move or copy the OpenCL `cl.hpp` file to the `/System/Library/Frameworks/OpenCL.framework/Headers/` directory.  I have tried with and without using `sudo`.  See the build [here](https://travis-ci.org/cdeterman/gpuR/builds/164726246).  How did you get the C++ header file there with the new security measures?

**Comment by dselivanov** [comment]
@cdeterman I copied `cl.hpp` as it is described in [wiki](https://github.com/cdeterman/gpuR/wiki/Build-Instructions-for-OSX#note-for-el-capitan-users).

**Comment by cdeterman** [comment]
@dselivanov I suspected this but was curious if any other way was successful.  I can't restart the Travis build environment to use that fix.  I will need to contact Travis CI to see if there is some other way to deal with it.  Maybe I can create another copy of the headers and point to it for the build.  What a pain...

**Comment by clmgit** [comment]
Note for El Capitan Users

If you are using OSX 11.11 (El Capitan), you may need to disable System Integrity Protection (SIP) temporarily to be able to copy cl.hpp to the System folder. To disable SIP:

as noted, this works:
Restart the computer holding cmd+R
Go to the Utilities menu and open a Terminal
On the Terminal, enter csrutil disable
Then restart the computer normally.
After copying the file, you can enable SIP by repeating the process, but this time entering the command csrutil enable.

**Comment by clmgit** [comment]
Thor:~ Chuck$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by clmgit** [comment]
RcppEigen’ version 0.3.2.9.0

**Comment by cdeterman** [comment]
@clmgit well the build works fine with the most recent El Capitan version using xcode8.  Is that the same as you?  I believe you can check the xcode version with:

```sh
/Developer/usr/bin/xcodebuild -version
```

I want to make sure I am matching your system as closely as I can with the [available options](https://docs.travis-ci.com/user/osx-ci-environment/).

**Comment by clmgit** [comment]
attached is the xcode version as well as the sdk's installed on my machine.  i examined the travis cl sdk's and found they have the mac 10.11 sdk installed for el capitan.  however, the attached file shows that apple installed the 10.12 sdk with xcode 8.  if this is the issue,  i suppose i could just upgrade to 10.12, which would save you a lot of effort.  Here is the note from apple community on this issue.  It essentially says when you upgrade xcode you must upgrade to its associated operating system version, which i did not.

Honestly I don't see how a developer like yourself can deal all this. 
[xcode_version.zip](https://github.com/cdeterman/gpuR/files/508543/xcode_version.zip)


jhowarth
Sep 15, 2016 7:39 AM
(in response to jhowarth)
Just to be clear, Apple policy since Xcode 7 has been to only distribute the newest SDK with Xcode.app. So when a new OS release arrives, Xcode will build with that release's SDK even on the previous OS release. Unfortunately, this change was never extended to the SDK installed in / by the assoicated Command Line Tools for the prior OS release.

**Comment by clmgit** [comment]
at this point, i am willing to go up to os 10.12, it might solve the problem.  i have no particular reason not to go up, just an excess of caution.

**Comment by cdeterman** [comment]
@clmgit if you want to upgrade that's fine.  The fact of the matter is that it still 'should' work.  I am truly at a loss at the moment because it the error is complaining about the Eigen library not having size_type.  Now clearly this shouldn't be a problem as this package has been built on numerous platforms across different OS.  I just can't seem to find a way to reproduce the problem.

**Comment by clmgit** [comment]
sorry for the mess!  i have an older macbook pro running a gpu.  your software installs fine and runs the little toy vignette. (its running os x 10.11.6 and xcode 7.3.1 with 7.3.1 command line tools.)  all i did was add the required cl.hpp, then: 
brew install viennacl
install.packages('RViennaCL')
install.packages('gpuR')
Those worked fine.

for my mac pro, still not working, i went back to xcode 7.3.1 and command line tools 7.3.1, and installed your development code without success (same errors).  it seems possible there is a conflict generated by something i have added to R or OS X along the way, perhaps i should start with a cleaner slate.  

thanks for your diligent efforts.
