### ISSUE TITLE
gpuMatrix subset methods failing with ranges

### ISSUE THREAD

**Issue by dselivanov** [cdeterman/gpuR#43]
Would be great to add support for slicing for ranges (and document limitations, because of GPU RAM latency):
```r
library(gpuR)
N = 128
A = matrix(rnorm(N * N), nrow = N)
G = gpuMatrix(A, type = 'float') # or vclMatrix
# works
G[1, 4]
# all below don't work
# Error in eval(substitute(expr), envir, enclos) : expecting a single value
G[1:4, ]
G[, 1:4]
G[1:4, 1:4]
```
Also would be great to have docs to understand how matrices stored in GPU: row-major or column-major.

**Comment by cdeterman** [comment]
There are actually `slice` and `block` methods for vector and matrix objects respectively.   These methods are very briefly described in the `gpuR` vignette.

```r
vignette("gpuR", package = "gpuR")
```

I actually am surprised about the subsetting failing.  I thought I had unit tests for those but I guess not.  I will need to have a closer look.

Regarding the matrix storage, the default for ViennaCL is row-major.  I was intending to create another vignette 'Extending gpuR' for those interested in the internals and wishing to contribute.  Yet again, time has restricted what I have been able to accomplish lately.

**Comment by dselivanov** [comment]
> Regarding the matrix storage, the default for ViennaCL is row-major.
I suspected that. So good to know, because this is opposite to R column-major format.

**Comment by cdeterman** [comment]
Yes, it is the opposite of most frameworks I work with so it is a mind shift when writing different functions (especially OpenCL kernels).  I should point out though that column-major storage is possible with ViennaCL.  However, the OpenCL tuned kernels perform much better of row-major storage.  If you are curious as to why you would need to ask the ViennaCL author.

**Comment by cdeterman** [comment]
@dselivanov  Since this is now more related to the failing subset methods I will be changing the issue title.

**Comment by cdeterman** [comment]
The previous commit should address your wish for matrix subsets.  Again, this is distinct from the `block` options which explicitly reuse the existing memory.  These new methods will pull the desired data back to R and be expressed as a distinct R `matrix` object.
