### ISSUE TITLE
Issue with benchmarking

### ISSUE THREAD

**Issue by dselivanov** [cdeterman/gpuR#44]
Results from my laptop with Intel Iris Pro card and dev version of pkg.
I can't explain this, but seems GPU backend returns control to R interpreter before materializing result in GPU memory (check median values):

``` r
library(gpuR)
library(microbenchmark)

N = 1024
A = matrix(rnorm(N * N), nrow = N)
G = vclMatrix(A, type = 'float')


microbenchmark(
  {GG <- crossprod(G);},
  {AA <- crossprod(A);}, 
  times = 100
  )
#Unit: milliseconds
#                       expr       min        lq      mean   median        uq      max neval
# {     GG <- crossprod(G) }  2.855407  3.261372  6.636427  3.46686  4.065919 64.58746   100
# {     AA <- crossprod(A) } 12.821452 14.132459 16.936565 15.33515 16.685954 57.84831   100
microbenchmark(
  {GG <- crossprod(G); GG[1]},
  {AA <- crossprod(A); AA[1]}, 
  times = 100
)
#Unit: milliseconds
#                                 expr      min       lq     mean   median       uq      max neval
# {     GG <- crossprod(G)     GG[1] } 20.43659 25.42089 26.19543 26.43395 27.38519 30.57564   100
# {     AA <- crossprod(A)     AA[1] } 12.41177 14.07693 17.03150 16.03094 17.82994 68.36778   100
```

For example results with larger matrix:

``` r
N = 1024 * 4
A = matrix(rnorm(N * N), nrow = N)
G = vclMatrix(A, type = 'float')
microbenchmark(
  {GG <- crossprod(G);}, times = 10
)
#Unit: milliseconds
#                       expr      min       lq     mean   median      uq      max neval
# {     GG <- crossprod(G) } 3.044952 3.150829 28.66298 3.572825 4.44852 249.6691    10
```

Note that `lq`, `uq` are similar to previous experiment with smaller matrix...

**Comment by dselivanov** [comment]
So, the question is whether timings in parallelR blog post were correct... 300x speed up over openBLAS or Intel MKL look too good to be true...

**Comment by dselivanov** [comment]
But of course I would prefer to be wrong in my hypothesis 😀

**Comment by cdeterman** [comment]
@dselivanov the reason the speed is so dramatic is because the data is **already residing on** the GPU and then **remains** on the GPU.  When you add the accessor `GG[1]` you are now copying memory back to the CPU.  These data transfers are serious bottlenecks depending upon the device.  Although the documentation needs updating, this prior [ViennaCL doc](http://viennacl.sourceforge.net/viennacl-manual-current.pdf) on pages 12-14 it is mentioned that individual element access on the GPU is very slow. 

I wanted to make it clear regarding the location of the data is the important aspect here.  It is ideal to keep data on the GPU as long as possible before moving it back to the CPU.  Perhaps this wasn't made completely clear...

**Comment by dselivanov** [comment]
@cdeterman actually docs about `vclMatrix` are very clear. I didn't know that accessor `G[1]` copies all matrix from device to host (thought just one element)... But for multiplications it is strange to receive similar timings for 1024*1024 matrix crossprod and 4096*4096 matrix crossprod.

**Comment by cdeterman** [comment]
It should only be the one element.  I'm really not sure why it is so slow.  I would need to do some experiments with raw ViennaCL code to know for sure.  Regarding the scaling, that was my impression too but the results all appear to line up correctly with my unit tests.  I know GPU's are supposed to scale well but benchmarking is a continual work in progress.

**Comment by dselivanov** [comment]
I will also try to run benchmarks on other machines.

**Comment by dselivanov** [comment]
I created p2 GPU machine on AWS (Tesla k80). Will need more time for testing. Hope will have some results on weekend.

**Comment by dselivanov** [comment]
closing in favor of #69
