### ISSUE TITLE
Rsymphony support

### ISSUE THREAD

**Issue by jholderieath** [cdeterman/gpuR#46]
I am loving gpuR, I would like to request that you add support for using the Rsymphony package.  Rsymphony is 
SYMPHONY is an open source solver for solving mixed integer linear programs (MILPs). The current
version can be found at https://projects.coin-or.org/SYMPHONY. Package Rsymphony
uses the C interface of the callable library provided by SYMPHONY, and supplies a high level
solver function in R using the low level C interface.

**Comment by cdeterman** [comment]
I'm glad you are finding gpuR useful.  Regarding SYMPHONY support it isn't quite that simple.  GPU computing requires completely different algorithms to use the different architecture (e.g. OpenCL kernels).  As such, the C API for SYMPHONY would require me to move the data back to the CPU to be analyzed thus defeating the purpose of using gpuR.  Unfortunately until either SYMPHONY or another MILP is implemented with GPU support I can't link to it.  There are some linear solvers within the `develop` version of the package and could potentially be added in the future however.  Contributions are always welcome as well.
