### ISSUE TITLE
Additional math functions

### ISSUE THREAD

**Issue by dselivanov** [cdeterman/gpuR#47]
I will try to write tiny deep neural network project with different backends - gpu with gpuR (on top of `vclMatrix`) or cpu with blas. Need some more math functions:
- [x] `sign`
- [x] `max`, `min`
- [x] `pmax`, `pmin`
to be continued... 

Probably I can do similarly as it done with existing math functions. Will take a look when will have time.

**Comment by cdeterman** [comment]
Glad you have interest here.  I actually have some local code for doing exactly this, hence the [gpuRNN](https://github.com/gpuRcore/gpuRNN) repository.  I thought I had `max` and `min` already implemented though???    The OpenCL kernels for the others `sign`, `pmax`, and `pmin` should be relatively straightforward.

**Comment by dselivanov** [comment]
@cdeterman correct, `min`, `max` implemented.

**Comment by cdeterman** [comment]
I think I want to have this scheduled for release 1.3.  The next iteration 1.2 is long overdo and I want to finish up the few things remaining for it before adding more additional features.

**Comment by cdeterman** [comment]
@dselivanov `sign` is now implemented for all objects in 'develop'.

**Comment by cdeterman** [comment]
@dselivanov `pmax` and `pmin` also implemented now.  Feel free to experiment and let me know how it goes.
