### ISSUE TITLE
gpuR package installation

### ISSUE THREAD

**Issue by YassGuenn** [cdeterman/gpuR#49]
Hello,

I tried to install the gpuR package on my Windows computer, after having downloaded the CUBA toolkit, but it didn’t work. I also installed Rtools and changed the system PATH. I got a message telling me that the package “is only available in source form, and may need compilation of C/C++/Fortran”. I tried to install the package with the source file, but it wasn’t more successful.

Do you know how to fix my problem ?

Kind regards,

Yassin

**Comment by cdeterman** [comment]
Hello again Yassin,

Can you provide the output from the attempted package installation?

**Comment by YassGuenn** [comment]
Yes, of course :

> install.packages("gpuR")

Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘gpuR’
  These will not be installed

When I try to use the source file to install the package, I get this message :

> install.packages("~/R - Packages/gpuR_1.1.2.tar.gz", repos = NULL, type = "source")

'\\f-sokaris\home2$\a004184\MyDocs'
CMD.EXE a ‚t‚ d‚marr‚ avec le chemin d'accŠs comme r‚pertoire en
cours. Les chemins d'accŠs UNC ne sont pas prise en charge. Utilisation
du r‚pertoire Windows par d‚faut.
* installing *source* package 'gpuR' ...
** package 'gpuR' correctement décompressé et sommes MD5 vérifiées
Warning: l'exécution de la commande 'sh ./configure.win' renvoie un statut 127
ERROR: configuration failed for package 'gpuR'
* removing 'D:/Public/Programme/R-3.3.1/library/gpuR'
* restoring previous 'D:/Public/Programme/R-3.3.1/library/gpuR'
Warning in install.packages :
  running command '"D:/Public/Programme/R-3.3.1/bin/x64/R" CMD INSTALL -l "D:\Public\Programme\R-3.3.1\library" "//f-sokaris/home2$/a004184/MyDocs/R-PACK~1/gpuR_1.1.2.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘//f-sokaris/home2$/a004184/MyDocs/R-PACK~1/gpuR_1.1.2.tar.gz’ had non-zero exit status


Kind regards,

Yassin

**Comment by cdeterman** [comment]
Try installing my most recent development version with the following call

```r
devtools::install_github('cdeterman/gpuR', ref = 'develop')
```

If that doesn't work, please report back the output again.

**Comment by YassGuenn** [comment]
Thank you for your help.
Unfortunately, it did not work and I got the following message : 

> devtools::install_github('cdeterman/gpuR', ref = 'develop')
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name

**Comment by cdeterman** [comment]
@YassGuenn well that is strange.  Is your internet working?  Can you install any other packages at all even via `install.packages` currently?  That isn't a problem with `gpuR` but with your network or with your `devtools` install.

**Comment by YassGuenn** [comment]
Yes you are right, I was not connected to the right network when I computed the last code. With the right network (which allows to install packages via  install.packages), I got this following message :+1: 

> devtools::install_github('cdeterman/gpuR', ref = 'develop')

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

**Comment by cdeterman** [comment]
According the issue posted [here](https://github.com/hadley/devtools/issues/1079) you should restart R and reinstall `curl` and `httr`.

**Comment by YassGuenn** [comment]
Ok, that is what I did, and now I have the following message :

> devtools::install_github('cdeterman/gpuR', ref = 'develop')

Downloading GitHub repo cdeterman/gpuR@develop
from URL https://api.github.com/repos/cdeterman/gpuR/zipball/develop
Installing gpuR
"D:/Public/Programme/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/a004184/AppData/Local/Temp/RtmpCGyEZ1/devtools18dc7df34de5/cdeterman-gpuR-1cfee03" --library="D:/Public/Programme/R-3.3.1/library" --install-tests 

* installing *source* package 'gpuR' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
Erreur : package 'RViennaCL' 1.7.1-1 trouvé, mais >= 1.7.1.3 est nécessaire pour 'cdeterman-gpuR-1cfee03'
* removing 'D:/Public/Programme/R-3.3.1/library/gpuR'
* restoring previous 'D:/Public/Programme/R-3.3.1/library/gpuR'
Error: Command failed (1)



It is suggesting that I have downloaded the wrong version of the RViennaCL, but I installed the last release...

**Comment by cdeterman** [comment]
Ah, yes, this keeps coming up but it is my fault.  I will be releasing another version of `RViennaCL` before I release the newest `gpuR` (hopefully very soon).  You can install it easily with

```r
devtools::install_github('cdeterman/RViennaCL')`
```

**Comment by YassGuenn** [comment]
It works ! Thank you for your help.

Kind regards, 

Yassin

**Comment by thomasclifford** [comment]
Good day to you.
I am now getting an error when trying 
devtools::install_github('cdeterman/gpuR', ref = 'develop')
it returns:
Downloading GitHub repo cdeterman/gpuR@develop
from URL https://api.github.com/repos/cdeterman/gpuR/zipball/develop
Installing gpuR
Installation failed: error reading from connection
Have you moved or updated the master at this point ?
When I use regular install.packages("gpuR"), it used to prompt me to install from source, 
but today I'm getting the same error as above, 'error reading from connection.
Browsing to 
https://api.github.com/repos/cdeterman/gpuR/zipball/develop
prompts me to download the zip file.
Would I be able to install.packages("<dir-to-zipfile>/cdeterman-gpuR-v2.0.0-60-ge780286.zip", type = "source")  ?

**Comment by cdeterman** [comment]
@thomasclifford odd, no I have not moved anything.  It should work fine installing directly with `devtools` like that.  I am not sure at the moment.  Perhaps try again another time?  Regarding the zip file, yes, you should be able to simply download from the `develop` branch and manually install as well.

**Comment by seekerquoc** [comment]
Hello,

When i installed it on window 10 64bit and it show me this error with this command:
**### devtools::install_github('cdeterman/gpuR', ref = 'develop')**
* installing *source* package 'gpuR' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'gpuR'
* removing 'C:/Users/QUOC/Documents/R/win-library/3.5/gpuR'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by cdeterman** [comment]
@seekerquoc do you have Rtools installed?

**Comment by seekerquoc** [comment]
sorry when i restarted R studio, its working well

ty so much

**Comment by NickSEC** [comment]
Folks,
     This gpuR package loos very nice!  Just one problem - when I tried to install Rcpp, it installs version 12.7, which is the latest that is on the CRAN site.  However, the installation error tells me that version 12.15 is required.  Where on CRAN is this version??  I hope that finding it will be the final step in installing gpuR.

Nick.

**Comment by NickSEC** [comment]
> devtools::install_github('cdeterman/gpuR', ref = 'develop')
Downloading GitHub repo cdeterman/gpuR@develop
from URL https://api.github.com/repos/cdeterman/gpuR/zipball/develop
Installing gpuR
"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Analysis/AppData/Local/Temp/Rtmp8aSpaX/devtools1e14673a5d7/cdeterman-gpuR-a42f75d"  \
  --library="C:/Users/Analysis/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'gpuR' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
Error: package 'Rcpp' 0.12.7 was found, but >= 0.12.15 is required by 'cdeterman-gpuR-a42f75d'
* removing 'C:/Users/Analysis/Documents/R/win-library/3.3/gpuR'
Error: Command failed (1)

**Comment by jsancheg** [comment]
Hello,

After downloading the CUDA toolkit, I tried to install the gpuR package on my computer with Windows 10 as OS and R version 4.2, but it didn’t work.  I run the line install.packages("gpuR") and obtain this message. 

Warning in install.packages :
  package ‘gpuR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

then, I tried devtools::install_github('cdeterman/gpuR', ref = 'develop') obtained the following messages.


  Warning: file 'gpuR/cleanup' did not have execute permissions: corrected
   Warning: file 'gpuR/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/Jorge/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency 'assertive' is not available for package 'gpuR'
* removing 'C:/Users/Jorge/AppData/Local/R/win-library/4.2/gpuR'
Warning messages:
1: package ‘assertive’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Jorge\AppData\Local\R\win-library\4.2\00LOCK\Rcpp\libs\x64\Rcpp.dll to C:\Users\Jorge\AppData\Local\R\win-library\4.2\Rcpp\libs\x64\Rcpp.dll: Permission denied
3: In i.p(...) :
  installation of package ‘C:/Users/Jorge/AppData/Local/Temp/Rtmp8w1PG0/file56dc3a566be1/gpuR_2.0.3.tar.gz’ had non-zero exit status


Do you know how to fix my problem ?

Kind regards,

Jorge
