### ISSUE TITLE
gpuR and ViennaCL error under nvidia-docker

### ISSUE THREAD

**Issue by mjmg** [cdeterman/gpuR#52]
I'm getting the following errors when running functions under gpuR installed in a docker container loaded under nvidia-docker:

```
> detectPlatforms()
Error in eval(substitute(expr), envir, enclos) : 
ViennaCL: FATAL ERROR: ViennaCL encountered an unknown OpenCL error. 
Most likely your OpenCL SDK or driver is not installed properly. 
In some cases, this error is due to an invalid global work size or several kernel compilation errors.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net 
and supply at least the following information:`
- Operating System
- Which OpenCL implementation (AMD, NVIDIA, etc.)
- ViennaCL version 
Many thanks in advance!
```
gpuR was compiled and installed successfully along with ViennaCL headers during image building. The NVIDIA GPU driver was exposed to the docker container through nvidia-docker.

On the container, the following files are present:

```sh
bash-4.2$ ls -al /usr/local/cuda/lib64/ | grep CL
lrwxrwxrwx. 1 root root        14 Nov 17 12:28 libOpenCL.so -> libOpenCL.so.1
lrwxrwxrwx. 1 root root        16 Nov 17 12:28 libOpenCL.so.1 -> libOpenCL.so.1.0
lrwxrwxrwx. 1 root root        18 Nov 17 12:28 libOpenCL.so.1.0 -> libOpenCL.so.1.0.0
-rw-r--r--. 1 root root     25840 Sep  5 13:15 libOpenCL.so.1.0.0
```

```sh
bash-4.2$ ls -al /usr/local/nvidia/lib64 | grep cl
lrwxrwxrwx. 1  969  965       26 Nov 13 18:32 libnvidia-opencl.so.1 -> libnvidia-opencl.so.367.57
-rwxr-xr-x. 2 root root  8592200 Oct  4 03:41 libnvidia-opencl.so.367.57
```

My docker build logs and images are here:
[https://hub.docker.com/r/mjmg/centos-rstudio-opencpu-server-cuda/builds/](url)

**Comment by cdeterman** [comment]
Did you install from CRAN or the github version?  If the latter, did you have `CUDA_HOME` defined?  If not, I think the default installation is having trouble figuring out the ICD configuration.  It may help the package if it is compiled directly against the OpenCL installation with the environmental variable defined.

**Comment by mjmg** [comment]
The reference nvidia-docker Dockerfiles was missing the file "/etc/OpenCL/vendors/nvidia.icd" containing the line "libnvidia-opencl.so.1"

gpuR now works using nvidia provided OpenCL libraries.

Now I'm waiting for [https://github.com/gpuRcore/gpuRcuda/issues/2](url) to be resolved.
