### ISSUE TITLE
Matrix norm feature request

### ISSUE THREAD

**Issue by gumeo** [cdeterman/gpuR#53]
It would be nice to have a norm function similar to the one in base R. I have noticed that most of the functionality is there to achieve this, but I had not noticed a feature request for this particular function/operation.

**Comment by cdeterman** [comment]
Yes, this should be feasible.  I will mark it for version 1.3.0.

**Comment by gumeo** [comment]
Ok thanks!

**Comment by cdeterman** [comment]
@gumeo this is now available for `vclMatrix` objects in the 'develop' copy in this repository.  Feel free to test it out.  I still need to do the `gpuMatrix` methods.

**Comment by gumeo** [comment]
Ok, awesome great work! I will check it in the coming week :)

**Comment by cdeterman** [comment]
@gumeo Both `vclMatrix` and `gpuMatrix` are fully implemented.  Please note that spectral norm is still only possible for square matrices as the implementation for SVD has some problems in non-square matrices.
