### ISSUE TITLE
gpuR package build under windows

### ISSUE THREAD

**Issue by kajomano** [cdeterman/gpuR#54]
Hello Sir!

I tried to use the CRAN version of your package, but ran into the problem already discussed in #39.
I cloned the package from github and checked out the developement branch, but I ran into the following when building:

> In file included from ../inst/include/gpuR/getVCLptr.hpp:6:0,
                 from chol.cpp:11:
../inst/include/gpuR/dynEigenMat.hpp:31:61: error: expression 'new viennacl::matrix<ScalarType, viennacl::row_major, 1u>' is not a constant-expression

Tried to browse through the issues but did not find anything similar.

I also cloned and built the newest RViennaCL version directly from github. Trying to run your package on Windows, with an AMD HD 7300 gpu.

**Comment by cdeterman** [comment]
Can you provide your `sessionInfo()`?  I am curious about the relevant package versions.  Do you have the AMD SDK installed?  Please also provide at installation log prior to the compiler error you have provided as well.  This continues to build on my windows system as well as the appveyor CI that also uses the AMD SDK so I suspect something is off with your setup.

**Comment by kajomano** [comment]
Thank you for answering so quickly!
Here is the full installation log:

> ==> Rcmd.exe INSTALL --with-keep.source --no-multiarch gpuR
>
>* installing to library 'D:/userdata/mkajo/Installed/R/R-3.2.2/library'
>* installing *source* package 'gpuR' ...
>
>   **********************************************
>   WARNING: this package has a configure script
>         It probably needs manual configuration
>   **********************************************
>
>
>** libs
>g++ -m64 -std=c++0x -I"D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/include" -DNDEBUG -I. -
> I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS   -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/Rcpp/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RcppEigen/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RViennaCL/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/BH/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c chol.cpp -o chol.o
> In file included from ../inst/include/gpuR/getVCLptr.hpp:6:0,
>                  from chol.cpp:11:
> ../inst/include/gpuR/dynEigenMat.hpp:31:61: error: expression 'new viennacl::matrix<ScalarType, viennacl::row_major, 1u>' is not a constant-expression
> ../inst/include/gpuR/dynEigenMat.hpp:31:61: sorry, unimplemented: non-static data member initializers
> chol.cpp: In function 'void cpp_vclMatrix_custom_chol(SEXP, bool, int, SEXP, int, int) [with T = float, SEXP = SEXPREC*]':
> chol.cpp:113:97:   instantiated from here
> chol.cpp:64:16: warning: unused variable 'err' [-Wunused-variable]
> chol.cpp: In function 'void cpp_vclMatrix_custom_chol(SEXP, bool, int, SEXP, int, int) [with T = double, SEXP = SEXPREC*]':
> chol.cpp:116:98:   instantiated from here
> chol.cpp:64:16: warning: unused variable 'err' [-Wunused-variable]
> make: *** [chol.o] Error 1
> Warning: running command 'make -f "Makevars.win" -f "D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/etc/x64/Makeconf" -f "D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="gpuR.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o chol.o context.o device.o gpuEigenPtr.o gpuMatrix_igemm.o platform.o set_row_order.o solve.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o"' had status 2
> ERROR: compilation failed for package 'gpuR'
>
>* removing 'D:/userdata/mkajo/Installed/R/R-3.2.2/library/gpuR'
>* restoring previous 'D:/userdata/mkajo/Installed/R/R-3.2.2/library/gpuR'
>
>Exited with status 1.

Here is what is produced by sessionInfo():

> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=Hungarian_Hungary.1250  LC_CTYPE=Hungarian_Hungary.1250    LC_MONETARY=Hungarian_Hungary.1250
> [4] LC_NUMERIC=C                       LC_TIME=Hungarian_Hungary.1250    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RViennaCL_1.7.1.4
> 
> loaded via a namespace (and not attached):
> [1] tools_3.2.2

Which package versions are you interested in? I do have the AMD APP SDK 3.0 installed and I also set the relevant environmental variables

**Comment by cdeterman** [comment]
@kajomano I have made a small change that I think will address this problem in the `develop` version.  Please try to reinstall it once more.

If it fails can you provide the `g++` version (`g++ --version`)?  I assume it is from RTools but I don't see RTools anywhere in the build output.

Also, you aren't using the most recent R.  If you can upgrade, please try that (upgrading the RTools as well) and trying again is another possibility.

Unfortunately I can't seem to reproduce this error at the moment.  So I am only guessing here.

**Comment by kajomano** [comment]
Hello!
After pulling the new develop version it produced the following (different) error:

> ==> Rcmd.exe INSTALL --with-keep.source --no-multiarch gpuR
> 
> * installing to library 'D:/userdata/mkajo/Installed/R/R-3.2.2/library'
> * installing *source* package 'gpuR' ...
> 
>    **********************************************
>    WARNING: this package has a configure script
>          It probably needs manual configuration
>    **********************************************
> 
> 
> ** libs
> g++ -m64 -std=c++0x -I"D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS   -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/Rcpp/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RcppEigen/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RViennaCL/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/BH/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
> g++ -m64 -std=c++0x -I"D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS   -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/Rcpp/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RcppEigen/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/RViennaCL/include" -I"D:/userdata/mkajo/Installed/R/R-3.2.2/library/BH/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c chol.cpp -o chol.o
> In file included from ../inst/include/gpuR/getVCLptr.hpp:6:0,
>                  from chol.cpp:11:
> ../inst/include/gpuR/dynVCLVec.hpp:24:23: sorry, unimplemented: non-static data member initializers
> ../inst/include/gpuR/dynVCLVec.hpp:24:23: error: ISO C++ forbids in-class initialization of non-const static member 'shared'
> In file included from ../inst/include/gpuR/getVCLptr.hpp:8:0,
>                  from chol.cpp:11:
> ../inst/include/gpuR/dynEigenVec.hpp:22:71: error: expression 'new viennacl::vector_base<T, long long unsigned int, long long int>' is not a constant-expression
> ../inst/include/gpuR/dynEigenVec.hpp:22:71: sorry, unimplemented: non-static data member initializers
> chol.cpp: In function 'void cpp_vclMatrix_custom_chol(SEXP, bool, int, SEXP, int, int) [with T = float, SEXP = SEXPREC*]':
> chol.cpp:113:97:   instantiated from here
> chol.cpp:64:16: warning: unused variable 'err' [-Wunused-variable]
> chol.cpp: In function 'void cpp_vclMatrix_custom_chol(SEXP, bool, int, SEXP, int, int) [with T = double, SEXP = SEXPREC*]':
> chol.cpp:116:98:   instantiated from here
> chol.cpp:64:16: warning: unused variable 'err' [-Wunused-variable]
> make: *** [chol.o] Error 1
> Warning: running command 'make -f "Makevars.win" -f "D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/etc/x64/Makeconf" -f "D:/userdata/mkajo/INSTAL~1/R/R-32~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="gpuR.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o chol.o context.o device.o gpuEigenPtr.o gpuMatrix_igemm.o platform.o set_row_order.o solve.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o"' had status 2
> ERROR: compilation failed for package 'gpuR'
> * removing 'D:/userdata/mkajo/Installed/R/R-3.2.2/library/gpuR'
> * restoring previous 'D:/userdata/mkajo/Installed/R/R-3.2.2/library/gpuR'
> 
> Exited with status 1.

You are correct in that this did not use the mingw from Rstudio, but I could not figure out how to set it up correctly since Rtools was installed. Finally I uninstalled both R and Rtools and updated them to the current versions (MRO 3.3.4 and Rtools 34), which **solved the problem**. My best guess is that some flags were not set by default for the g++ that the installation was trying to use.

Anyway, thank you for the help!

**Comment by cdeterman** [comment]
Glad it solved the problem.  Please let me know if you encounter any further problems.
