### ISSUE TITLE
Allow for using custom OpenCL kernels

### ISSUE THREAD

**Issue by cdeterman** [cdeterman/gpuR#61]
It would be useful for users to be able to create there own functions from OpenCL kernels.  Right now, I do this manually within the package for any functionality that isn't within ViennaCL.  I am imagining this accomplished in a two steps.

1. Compile OpenCL kernel
2. Recall kernel to apply on gpuR objects

Something like the following would be ideal:

```r
cl_fun <- custom_opencl(kernel_file)
a <- vclMatrix(rnorm(16), 4, 4)

cl_fun(a)
```

This however omits the necessary c++ that usually is involved here to define the arguments.  This still needs to be sorted out.  I am creating this issue for tracking this initiative.

**Comment by clarkfitzg** [comment]
+1 This would be very helpful for the R programmer who wants to use OpenCL with a minimum of setup and fuss.

Another syntactic option that might be a little more flexible is the `apply` style:
```
apply(a, 1, cl_fun)
```

**Comment by cdeterman** [comment]
The first incarnation of this is now available in the `develop` branch.  Please see the vignette I have added [here](https://github.com/cdeterman/gpuR/blob/develop/inst/doc/custom_ocl_gpuR.pdf) for a basic instruction.  Any additional users testing this functionality would be appreciated.

**Comment by clarkfitzg** [comment]
I tried the hello world on Mac OSX and am seeing this error:

```
> gpuA <- vclVector(a, type = "float")
Error in cpp_cpuInfo(platform_idx, device_idx) : device is not a CPU
```

Same code works fine when I install from master branch.

**Comment by cdeterman** [comment]
@clarkfitzg is this just with the `develop` branch or is it related tot he `custom_opencl` function?

**Comment by clarkfitzg** [comment]
It appears to be unrelated to `custom_opencl`, as it happens before.

**Comment by cdeterman** [comment]
@clarkfitzg I will open a separate issue then #90.

**Comment by clarkfitzg** [comment]
Working fine on Mac OSX now. Nice work!

**Comment by cdeterman** [comment]
@clarkfitzg are you just referring to the `vclVector` bug or the `custom_opencl` in this comment?

**Comment by clarkfitzg** [comment]
Everything works so that I can run the `saxpy` example in the vignette.

**Comment by cdeterman** [comment]
@clarkfitzg Excellent, thank you
