### ISSUE TITLE
FATAL ERROR: CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by Tullio-DH** [cdeterman/gpuR#68]
Hello,

I'm trying to multiply a 2474x5 gpuMatrix by a 5x121237 one, so the product matrix should have about 3x10^8 elements. I'm getting the following error:

Error in cpp_gpuMatrix_gemm(A@address, B@address, C@address, 6L, A@.context_index -  : 
  ViennaCL: FATAL ERROR: CL_OUT_OF_RESOURCES 
 ViennaCL tried to launch a compute kernel, but the device does not provide enough resources. Try changing the global and local work item sizes.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net and supply at least the following information:
 * Operating System
 * Which OpenCL implementation (AMD, NVIDIA, etc.)
 * ViennaCL version
Many thanks in advance!
Called from: cpp_gpuMatrix_gemm(A@address, B@address, C@address, 6L, A@.context_index - 
    1)

Does it sound like I'm trying to use more gpu memory than provided? Could you suggest a quick way to verify that?

**Comment by cdeterman** [comment]
Well, a few things to check.  You can look at the available resources on the device with `gpuInfo()` and then estimate the amount of space taken up by the matrices.  A quick note though, the current implementation of ViennaCL pads matrices so they are multiples of 128.  

Another way to check would be to start a new R session and try to create the three matrices (two input matrices and the output matrix) as `vclMatrix` objects.  If you can create those three objects it should process normally.

If the above doesn't provide any clues, please provide your output of `gpuInfo()` and the dimensions of the matrices you are trying to multiply and I will try to reproduce on my machines.

**Comment by Tullio-DH** [comment]
Thanks for the tip, I was indeed going over memory with gpuMatrix.

Perhaps I ran into a bug: after downsizing the matrices, I made identical copies of my script, one running with gpu- and one with vclMatrix objects. The goal is to minimize some residuals, which I use Rcgmin for. I was curious to see which of the two implementations would run faster.

If you're not familiar with it, Rcgmin is a function from the package of the same name, taking as arguments a function f(x), its derivative df/dx, and an initial guess x_start.
I'm able to run compute f(x_start) and df/dx_start for both versions of the script, but Rcgmin doesn't seem to work with the vclMatrix objects:

> opt_Params <- Rcgmin(par = x_start,
+                      fn = cost_func,  #function to be minimized
+                      gr = params_grad, #analytical derivative of the function
+                      control=list(trace=1) #verbose output
+                      )
Rcgminu -- J C Nash 2009 - unconstrained version CG min
an R implementation of Alg 22 with Yuan/Dai modification
Initial function value= 16274610 
Initial fn= 16274610 
1   0   1   16274610   last decrease= NA 
*************************
  Converged -- no progress on new CG cycle 
26   1   2   16274610   last decrease= NA 
*************************51   2   3   16274610   last decrease= NA 
*************************76   3   4   16274610   last decrease= NA 
*************************101   4   5   16274610   last decrease= NA 
**

(continues forever without doing anything)

**Comment by cdeterman** [comment]
@Tullio-DH it is difficult to say.  You should always be cautious when trying to pass these objects to other package functions.  All I can say at this point is that `Rcgmin` someone doesn't handle the objects correctly.  I would need to go in to the internals to parse this out and I unfortunately don't have the time currently to do so.  I'm sorry to say I can't help you at this time as it is more outside the scope of `gpuR`.  I will continue to leave this issue open in the hopes of readdressing it.

**Comment by cdeterman** [comment]
As debugging `Rcgmin` is outside the context of `gpuR` I am choosing to close this issue.  It is more appropriate to contact the `Rcgmin` maintainers to develop additional functionality.
