### ISSUE TITLE
Allow for 'synchronization'

### ISSUE THREAD

**Issue by cdeterman** [cdeterman/gpuR#69]
At the moment, the calls to the `vclMatrix` objects are asynchronous.  This is still very useful for users not wanting to have processing wait for calls to finish on the GPU.  That said, it would be useful to have a function to make it explicit that all prior GPU processing must finish by 'this' point before continuing.  It would also be useful for further benchmarking operations.

**Comment by dselivanov** [comment]
I think this is related to #44 ?

**Comment by cdeterman** [comment]
@dselivanov I believe you are correct.  @PengZhao has completed some additional, more intensive benchmarks regarding `gpuR` as well as the other existing GPGPU packages that will be posted on the ParallelR blog in the near future.  The main issue here is that the `vclMatrix` calls are asynchronous so they do look much faster than actually happening because it simply returns control back to the CPU.  I probably could have made this posting within that issue but I had forgotten about it with all the other things I currently have going on.
