### ISSUE TITLE
compile on mac os x 10.10 , r 3.2.1

### ISSUE THREAD

**Issue by newffy** [cdeterman/gpuR#7]
During installing 
devtools::install_github("cdeterman/RViennaCL")
is ok

devtools::install_github("cdeterman/gpuR")
throws error 

 installing *source* package ‘gpuR’ ...
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.1_1/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/RcppEigen/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/RViennaCL/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/BH/include"  -I../inst/include -fPIC  -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.1_1/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/RcppEigen/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/RViennaCL/include" -I"/usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/BH/include"  -I../inst/include -fPIC  -g -O2 -c detectCPUs.cpp -o detectCPUs.o
In file included from detectCPUs.cpp:6:
In file included from /usr/local/Cellar/r/3.2.1_1/R.framework/Versions/3.2/Resources/library/RViennaCL/include/CL/cl.hpp:158:
In file included from /System/Library/Frameworks/OpenCL.framework/Headers/opencl.h:14:
/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl_ext.h:136:29: error: unknown type name 'cl_image_desc'; did you mean 'cl_image_info'?
                      const cl_image_desc *           /* image_desc */,

**Comment by cdeterman** [comment]
@newffy thank you for trying the build on a Mac.  It appears that the opencl headers in the backend viennacl library are too old for your local opencl.  Try re-installing the RViennaCL package again and try to install gpuR again which should use your own local opencl headers.

**Comment by newffy** [comment]
thanks for quick response.
Now I have the next error:

* installing *source* package ‘gpuR’ ...
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I"/Users/newf/Library/R/3.2/library/Rcpp/include" -I"/Users/newf/Library/R/3.2/library/RcppEigen/include" -I"/Users/newf/Library/R/3.2/library/RViennaCL/include" -I"/Users/newf/Library/R/3.2/library/BH/include"  -I../inst/include -fPIC  -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I"/Users/newf/Library/R/3.2/library/Rcpp/include" -I"/Users/newf/Library/R/3.2/library/RcppEigen/include" -I"/Users/newf/Library/R/3.2/library/RViennaCL/include" -I"/Users/newf/Library/R/3.2/library/BH/include"  -I../inst/include -fPIC  -g -O2 -c detectCPUs.cpp -o detectCPUs.o
detectCPUs.cpp:4:10: fatal error: 'CL/cl.h' file not found
#include <CL/cl.h>
         ^
1 error generated.
make: *** [detectCPUs.o] Error 1
ERROR: compilation failed for package ‘gpuR’
* removing ‘/Users/newf/Library/R/3.2/library/gpuR’
Ошибка: Command failed (1)

maybe http://stackoverflow.com/questions/22261559/opencl-headers-missing-from-the-opencl-framework-in-os-x-mavericks 
is the same case?

**Comment by cdeterman** [comment]
@newffy could you look in the following directory on your Mac and confirm whether or not the `cl.hpp` file exists?

    /System/Library/Frameworks/OpenCL.framework/Headers/

**Comment by newffy** [comment]
```
ls -l /System/Library/Frameworks/OpenCL.framework/Headers/
total 88
-rw-r--r--  1 root  wheel  61551 27 фев 12:28 cl.h
-rw-r--r--  1 root  wheel  16605 27 фев 12:28 cl_ext.h
-rw-r--r--  1 root  wheel   5811 27 фев 12:28 cl_gl.h
-rw-r--r--  1 root  wheel   7217 27 фев 12:28 cl_gl_ext.h
-rw-r--r--  1 root  wheel  40965 27 фев 12:28 cl_platform.h
-rw-r--r--  1 root  wheel  16027 27 фев 12:28 gcl.h
-rw-r--r--  1 root  wheel   3099 27 фев 12:28 gcl_priv.h
-rw-r--r--  1 root  wheel    495 27 фев 12:28 opencl.h
```

**Comment by cdeterman** [comment]
@newffy Thank you, one more check then.  I need you to open the `cl.h` file with some text editor and search for the section `/* OpenCL Version */` around line 180.  It will look something like this:

    /* OpenCL Version */
    #define CL_VERSION_1_0
    #define CL_VERSION_1_1
    #define CL_VERSION_1_2

I just need to know what the top version is in that file.  In this example case the top version is 1.2.  If this is the case you will need to download the `cl.hpp` file from [Khronos here](https://www.khronos.org/registry/cl/api/1.2/cl.hpp) and place it in that directory with the other header files.  If you need a different version all the files on [here](https://www.khronos.org/registry/cl/).  I thought the Mac OpenCL headers would have the C++ bindings.  Sorry I don't have a Mac to do all this testing myself :(

**Comment by newffy** [comment]
It's
```
/* OpenCL Version */
#define CL_VERSION_1_0                              1
#define CL_VERSION_1_1                              1
#define CL_VERSION_1_2                              1
```

**Comment by cdeterman** [comment]
Okay, great, now download the `cl.hpp` file in that directory and try building from my git repo again.

**Comment by newffy** [comment]
Well... I've tried, without success:
```
ls -la /System/Library/Frameworks/OpenCL.framework/Headers/
total 312
drwxr-xr-x  11 root  wheel     374 22 авг 22:41 .
drwxr-xr-x   8 root  wheel     272  1 июл 10:25 ..
-rw-r--r--   1 root  wheel   61551 27 фев 12:28 cl.h
-rw-r--r--@  1 root  wheel  112900 22 авг 22:41 cl.hpp
-rw-r--r--   1 root  wheel   16605 27 фев 12:28 cl_ext.h
-rw-r--r--   1 root  wheel    5811 27 фев 12:28 cl_gl.h
-rw-r--r--   1 root  wheel    7217 27 фев 12:28 cl_gl_ext.h
-rw-r--r--   1 root  wheel   40965 27 фев 12:28 cl_platform.h
-rw-r--r--   1 root  wheel   16027 27 фев 12:28 gcl.h
-rw-r--r--   1 root  wheel    3099 27 фев 12:28 gcl_priv.h
-rw-r--r--   1 root  wheel     495 27 фев 12:28 opencl.h
```
```
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I"/Users/newf/Library/R/3.2/library/Rcpp/include" -I"/Users/newf/Library/R/3.2/library/RcppEigen/include" -I"/Users/newf/Library/R/3.2/library/RViennaCL/include" -I"/Users/newf/Library/R/3.2/library/BH/include"  -I../inst/include -fPIC  -g -O2 -c detectCPUs.cpp -o detectCPUs.o
In file included from detectCPUs.cpp:27:
../inst/include/gpuR/cl_helpers.hpp:8:10: fatal error: 'CL/cl.hpp' file not found
#include <CL/cl.hpp>
         ^
1 error generated.
make: *** [detectCPUs.o] Error 1
ERROR: compilation failed for package ‘gpuR’
* removing ‘/Users/newf/Library/R/3.2/library/gpuR’
```

**Comment by cdeterman** [comment]
Ok, I am trying some things out with a Mac build on travis ci.  I will report back once I successfully build the package. I am much closer but need to clarify a few more things.

**Comment by cdeterman** [comment]
@newffy try once more now to install the package.  I now have a travis ci machine where it is building successfully.  Since you already have the `cl.hpp` file it should work.  Let me know how it goes.

**Comment by cdeterman** [comment]
@newffy did you ever get a chance to try and install `gpuR` again?  I am successfully building on Travis CI OSX machines so unless you say otherwise I will assume it works for you and I will close this issue tomorrow.

**Comment by newffy** [comment]
Hello!
I've tried now it, it's installed correctly now, thanks!
I still didn't tried it in work and I suppose I'll have the same problem as with others libraries with watchdog timer (I mean "Run time limit on kernels: Yes" in output of deviceQuery util)

**Comment by cdeterman** [comment]
Glad that it works for you now.  I'm not very familiar with the watchdog timer (I am not a avid Mac user).  If you run in to specific issues when using the package feel free to submit an issue and I will try to address it.  Just realize I don't have an actual mac to troubleshoot these things so I may not be able to solve the problem.  Will be interesting to see how it works for you and others as this package gets more exposure.
