### ISSUE TITLE
I can not install the "gpuR" package

### ISSUE THREAD

**Issue by click7254** [cdeterman/gpuR#71]
The following error has occurred 
In file included from utils-vcl.cpp:7:
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids initialization of member ‘shared’
../inst/include/gpuR/dynVCLVec.hpp:24: error: making ‘shared’ static
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<int>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = int]’
utils-vcl.cpp:89:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<int>::shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<float>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = float]’
utils-vcl.cpp:91:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<float>::shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<double>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = double]’
utils-vcl.cpp:93:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<double>::shared’
make: *** [utils-vcl.o] 오류 1
ERROR: compilation failed for package ‘gpuR’

How should i solve it?

R Version = "3.3.2"

CUDA Version = "cuda-8.0"

CPU INFO = "Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz"

GPU INFO = 
[root@localhost local]# nvidia-smi
Mon Apr  3 16:51:00 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K6000        Off  | 0000:84:00.0     Off |                  Off |
|  0%   37C    P0    35W / 225W |      0MiB / 12204MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

bash_profile
 .bash_profile

Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

User specific environment and startup programs

export JAVA_HOME=/usr/data/java
export PATH=.:$JAVA_HOME/bin:/usr/local/cuda-8.0/bin:$PATH
export CLASSPATH="."
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH
PATH=$PATH:$HOME/bin

export PATH

ld.so.conf
include ld.so.conf.d/*.conf
/usr/local/cuda-8.0/lib64

00install.out 
* installing *source* package ‘gpuR’ ...
** 패키지 ‘gpuR’는 성공적으로 압축해제되었고, MD5 sums 이 확인되었습니다
OPENCL_FLAGS not set, using default -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS  -DCL_HPP_TARGET_OPENCL_VERSION=120
Linux OS
found OpenCL library
Checking OpenCL C++ API
OPENCL_INC not set, using default include directory /usr/include
cl2.hpp header exists

*********** Generated Makevars file ***********
CXX_STD=CXX11
PKG_CPPFLAGS=-I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP
PKG_CXXFLAGS=
PKG_LIBS=-lOpenCL
BUILD_LIB=

$(SHLIB): $(BUILD_LIB)

../inst/include/loader/libOpenCL.a:
	cd ../inst/include/loader/ && $(MAKE) libOpenCL.a \
	CC="$(CC)" CFLAGS="$(ALL_CFLAGS)" AR="$(AR)" RM="$(RM)" \
	ICD_OS=icd_linux
***********************************************
** libs
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c chol.cpp -o chol.o
chol.cpp: In function ‘void cpp_vclMatrix_custom_chol(SEXPREC*, bool, int, SEXPREC*, int, int) [with T = float]’:
chol.cpp:112:   instantiated from here
chol.cpp:63: warning: unused variable ‘err’
chol.cpp: In function ‘void cpp_vclMatrix_custom_chol(SEXPREC*, bool, int, SEXPREC*, int, int) [with T = double]’:
chol.cpp:115:   instantiated from here
chol.cpp:63: warning: unused variable ‘err’
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c context.cpp -o context.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c device.cpp -o device.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c gpuEigenPtr.cpp -o gpuEigenPtr.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c gpuMatrix_igemm.cpp -o gpuMatrix_igemm.o
gpuMatrix_igemm.cpp: In function ‘void cpp_gpuMatrix_custom_igemm(SEXPREC*, bool, SEXPREC*, bool, SEXPREC*, bool, SEXPREC*, int, int)’:
gpuMatrix_igemm.cpp:59: warning: unused variable ‘err’
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c platform.cpp -o platform.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c set_row_order.cpp -o set_row_order.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c solve.cpp -o solve.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c trunc_gpuMat.cpp -o trunc_gpuMat.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c utils-vcl.cpp -o utils-vcl.o
In file included from utils-vcl.cpp:7:
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids initialization of member ‘shared’
../inst/include/gpuR/dynVCLVec.hpp:24: error: making ‘shared’ static
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<int>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = int]’
utils-vcl.cpp:89:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<int>::shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<float>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = float]’
utils-vcl.cpp:91:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<float>::shared’
../inst/include/gpuR/dynVCLVec.hpp: In instantiation of ‘dynVCLVec<double>’:
utils-vcl.cpp:36:   instantiated from ‘int cpp_vclVector_size(SEXPREC*) [with T = double]’
utils-vcl.cpp:93:   instantiated from here
../inst/include/gpuR/dynVCLVec.hpp:24: error: ISO C++ forbids in-class initialization of non-const static member ‘dynVCLVec<double>::shared’
make: *** [utils-vcl.o] 오류 1
ERROR: compilation failed for package ‘gpuR’
* removing ‘/usr/local/gpuR.Rcheck/gpuR’

**Comment by cdeterman** [comment]
@click7254 thank for reporting the problem.  Please try installing the 'develop' version with `devtools::install_github('cdeterman/gpuR', ref = 'develop')`.  My latest commit should have fixed this problem.

**Comment by click7254** [comment]
Thank you for your reply. 
I try installing the 'develop' version. but another error has occurred.
please tell me how to solve it?

devtools::install_github('cdeterman/gpuR', ref = 'develop')
Downloading GitHub repo cdeterman/gpuR@develop
from URL https://api.github.com/repos/cdeterman/gpuR/zipball/develop
Installing gpuR
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/Rtmp5GHTqS/devtools3b1e19ee0735/cdeterman-gpuR-590b927'  \
  --library='/usr/lib64/R/library' --install-tests

* installing *source* package ‘gpuR’ ...
OPENCL_FLAGS not set, using default -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS  -DCL_HPP_TARGET_OPENCL_VERSION=120
Linux OS
found OpenCL library
Checking OpenCL C++ API
OPENCL_INC not set, using default include directory /usr/include
cl2.hpp header exists

*********** Generated Makevars file ***********
CXX_STD=CXX11
PKG_CPPFLAGS=-I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP
PKG_CXXFLAGS=
PKG_LIBS=-lOpenCL
BUILD_LIB=

$(SHLIB): $(BUILD_LIB)

../inst/include/loader/libOpenCL.a:
        cd ../inst/include/loader/ && $(MAKE) libOpenCL.a \
        CC="$(CC)" CFLAGS="$(ALL_CFLAGS)" AR="$(AR)" RM="$(RM)" \
        ICD_OS=icd_linux
***********************************************
** libs
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -I'/usr/include/' -DHAVE_CL_CL2_HPP -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/RViennaCL/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c chol.cpp -o chol.o
In file included from ../inst/include/gpuR/getVCLptr.hpp:8,
                 from chol.cpp:11:
../inst/include/gpuR/dynEigenVec.hpp:22: error: ‘new’ cannot appear in a constant-expression
../inst/include/gpuR/dynEigenVec.hpp:22: error: ISO C++ forbids initialization of member ‘vclA’
../inst/include/gpuR/dynEigenVec.hpp:22: error: making ‘vclA’ static
chol.cpp: In function ‘void cpp_vclMatrix_custom_chol(SEXPREC*, bool, int, SEXPREC*, int, int) [with T = float]’:
chol.cpp:113:   instantiated from here
chol.cpp:64: warning: unused variable ‘err’
chol.cpp: In function ‘void cpp_vclMatrix_custom_chol(SEXPREC*, bool, int, SEXPREC*, int, int) [with T = double]’:
chol.cpp:116:   instantiated from here
chol.cpp:64: warning: unused variable ‘err’
make: *** [chol.o] 오류 1
ERROR: compilation failed for package ‘gpuR’
* removing ‘/usr/lib64/R/library/gpuR’
에러: Command failed (1)

**Comment by cdeterman** [comment]
@click7254 sorry for the long delay, I had forgotten about this problem.  I have pushed a commit that I believe should solve this problem.  Please try to reinstall the 'develop' branch once again when you have some time.

**Comment by cdeterman** [comment]
As far as I know, I can no longer reproduce this error.  Please note if the problem does not appear to be fixed and the issue can be reopened.

**Comment by avallark** [comment]
i get the following error. Similar to the last error of @click7254 
My system specs are
```
AMD FX 8350
NVIDIA GeForce 760 Ti CUDA
Ubuntu 20.04
Cuda toolkit, nvidia-opencl-dev
```
error logs
```
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:804:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, 1, -1, false>; Src = Eigen::Matrix<double, -1, 1>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:782:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, 1, -1, false>; Src = Eigen::Matrix<double, -1, 1>]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/Assign.h:66:28:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, 1>; Derived = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, 1, -1, false>]’
../inst/include/gpuR/dynEigenMat.hpp:188:30:   required from ‘void dynEigenMat<T>::setRow(SEXP, int) [with T = double; SEXP = SEXPREC*]’
../inst/include/gpuR/dynEigenMat.hpp:383:16:   required from here
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h: In instantiation of ‘struct Eigen::internal::evaluator<Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true> >’:
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:736:20:   required from ‘void Eigen::internal::call_dense_assignment_loop(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>; SrcXprType = Eigen::Matrix<double, -1, 1>; Functor = Eigen::internal::assign_op<double, double>]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:879:31:   required from ‘static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>; SrcXprType = Eigen::Matrix<double, -1, 1>; Functor = Eigen::internal::assign_op<double, double>; Weak = void]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:836:49:   required from ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>; Src = Eigen::Matrix<double, -1, 1>; Func = Eigen::internal::assign_op<double, double>]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:804:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>; Src = Eigen::Matrix<double, -1, 1>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:782:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>; Src = Eigen::Matrix<double, -1, 1>]’
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/Assign.h:66:28:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, 1>; Derived = Eigen::Block<Eigen::Ref<Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>]’
../inst/include/gpuR/dynEigenMat.hpp:192:30:   required from ‘void dynEigenMat<T>::setCol(SEXP, int) [with T = double; SEXP = SEXPREC*]’
../inst/include/gpuR/dynEigenMat.hpp:383:16:   required from here
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]
during IPA pass: icf
chol.cpp:123:1: internal compiler error: Segmentation fault
  123 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make: *** [/usr/lib/R/etc/Makeconf:177: chol.o] Error 1
ERROR: compilation failed for package ‘gpuR’
* removing ‘/usr/local/lib/R/site-library/gpuR’
Error: Failed to install 'gpuR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpN0TxB4/file10fac5b69baa0/gpuR_2.0.3.tar.gz’ had non-zero exit status
```
Is there a reason for this?
