### ISSUE TITLE
Crashing R on AMD "Bonaire"

### ISSUE THREAD

**Issue by znmeb** [cdeterman/gpuR#77]
System is Fedora 25, all open source drivers. ViennaCL and gpuR are both from GitHub / the master branch.

```
> library(gpuR)
Number of platforms: 2
- platform: Mesa: OpenCL 1.1 Mesa 13.0.4
  - gpu index: 0
    - AMD BONAIRE (DRM 2.49.0 / 4.10.11-200.fc25.x86_64, LLVM 3.9.1)
- platform: The pocl project: OpenCL 2.0 pocl 0.14-pre, LLVM 3.9.1
  - gpu index: 0
    - pthread-AMD FX(tm)-8350 Eight-Core Processor
checked all devices
completed initialization
gpuR 1.2.2

Attaching package: ‘gpuR’

The following objects are masked from ‘package:base’:

    colnames, svd

> set.seed(123)
> gpuA <- gpuMatrix(rnorm(16), nrow=4, ncol=4)
> gpuB <- gpuA %*% gpuA
LLVM ERROR: Cannot select: 0x55c65eccccc0: f64 = fpow 0x55c65ecd3b00, 0x55c65eccf870
  0x55c65ecd3b00: f64 = bitcast 0x55c65eccaf40
    0x55c65eccaf40: v2i32,ch = load<LD8[%arrayidx(addrspace=1)](tbaa=<0x55c65f89a848>)> 0x55c65ec86180, 0x55c65eccb3a0, undef:i64
      0x55c65eccb3a0: i64 = add 0x55c65ecb21c0, 0x55c65eccb870
        0x55c65ecb21c0: i64,ch = CopyFromReg 0x55c65ec86180, Register:i64 %vreg66
          0x55c65eccf9c0: i64 = Register %vreg66
        0x55c65eccb870: i64 = shl 0x55c65ecd36a0, Constant:i32<3>
          0x55c65ecd36a0: i64 = sign_extend 0x55c65ecc7ea0
            0x55c65ecc7ea0: i32 = add 0x55c65ecccda0, 0x55c65eccfc60
              0x55c65ecccda0: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg19
                0x55c65ecb1ba0: i32 = Register %vreg19
              0x55c65eccfc60: i32 = mul 0x55c65ecb20e0, 0x55c65ecb1c10
                0x55c65ecb20e0: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg25
                  0x55c65eccb9c0: i32 = Register %vreg25
                0x55c65ecb1c10: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg70
                  0x55c65eccda50: i32 = Register %vreg70
          0x55c65ecc8a70: i32 = Constant<3>
      0x55c65eccb5d0: i64 = undef
  0x55c65eccf870: f64 = bitcast 0x55c65ecc7ff0
    0x55c65ecc7ff0: v2i32,ch = load<LD8[%arrayidx16(addrspace=1)](tbaa=<0x55c65f89a848>)> 0x55c65ec86180, 0x55c65ecd00c0, undef:i64
      0x55c65ecd00c0: i64 = add 0x55c65eccd4a0, 0x55c65ecd3f60
        0x55c65eccd4a0: i64,ch = CopyFromReg 0x55c65ec86180, Register:i64 %vreg72
          0x55c65ecc85a0: i64 = Register %vreg72
        0x55c65ecd3f60: i64 = shl 0x55c65eccf3a0, Constant:i32<3>
          0x55c65eccf3a0: i64 = sign_extend 0x55c65eccd350
            0x55c65eccd350: i32 = add 0x55c65eccffe0, 0x55c65ecccbe0
              0x55c65eccffe0: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg20
                0x55c65ecc84c0: i32 = Register %vreg20
              0x55c65ecccbe0: i32 = mul 0x55c65ecb20e0, 0x55c65eccb250
                0x55c65ecb20e0: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg25
                  0x55c65eccb9c0: i32 = Register %vreg25
                0x55c65eccb250: i32,ch = CopyFromReg 0x55c65ec86180, Register:i32 %vreg76
                  0x55c65eccb410: i32 = Register %vreg76
          0x55c65ecc8a70: i32 = Constant<3>
      0x55c65eccb5d0: i64 = undef
In function: element_op
[znmeb@AlgoCompSynth ~]$ 
```

The system is dual-booted now (Fedora 25 and 26 alpha). The 26 install has newer drivers but still crashes. I'm guessing this is a driver problem; if you think it is, let me know and I'll file a bug on Fedora 26 alpha.

**Comment by cdeterman** [comment]
This looks like a lower level problem I am not familiar with.  @karlrupp do you have any insight regarding this?

**Comment by karlrupp** [comment]
That looks like a problem with the `Mesa: OpenCL 1.1 Mesa 13.0.4` platform, as their OpenCL just-in-time compiler doesn't implement (or know how to generate binary code for) the function `pow()`

**Comment by znmeb** [comment]
@karlrupp @cdeterman I have it on Fedora 26 as well - it's still OpenCL 1.1 but it's Mesa 17.0.2. I'd rather troubleshoot this on Fedora 26; it's in alpha and if it's a _Fedora_ problem it will get more attention on F26 ;-).

I ran the test suite last night and it's producing lots of failures; the logs are way too large to post here though. I have enough disk space on this machine to put up a "known good" Linux as a third boot option if either of you can recommend one. I'm thinking maybe Manjaro because it's Arch-based.

Here's the `clinfo` details; note that `clpeak` doesn't even run on either F25 or F26 against the "Clover" platform.

```
  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD BONAIRE (DRM 2.49.0 / 4.11.0-0.rc7.git0.1.fc26.x86_64, LLVM 3.9.1)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 17.0.2
  Driver Version                                  17.0.2
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Available                                Yes
  Device Profile                                  FULL_PROFILE
  Max compute units                               14
  Max clock frequency                             1075MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Compiler Available                              Yes
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2142670848 (1.996GiB)
  Error Correction support                        No
  Max memory allocation                           1499869593 (1.397GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        1499869593 (1.397GiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64
```

**Comment by znmeb** [comment]
Well ... there are only 134 bugs referencing OpenCL on the Bugzilla search for Mesa drivers: <https://bugs.freedesktop.org/buglist.cgi?bug_status=__open__&content=opencl&list_id=613081&order=changeddate%20DESC%2Cpriority%2Cbug_severity&query_format=specific>

**Comment by znmeb** [comment]
I finally have some free time to troubleshoot this in detail. I'm totally convinced it's an OpenCL driver problem though. I've tried several Linux distros, including the one AMD supports, Ubuntu 16.04.02 LTS. I tried it with the AMDGPU Pro drivers too. I haven't been able to get any of the open source OpenCL demos / benchmarks (clpeak and luxmark for openers) to work against my GPU. 

Otjher GPU stuff seems to work fine; WebGL works, for example, and I can see GPU activity in `radeon-top` when a WebGL site is playing.

By the way, I've switched distros again. I was on Ubuntu mostly because I was working on a project that used the Ubuntu GIS stack ... that's done and if I need to resurrect it I can run it in a VM. And Fedora's got too many upstream bugs, for example, in gdb.

So I'm now on Arch Linux. The Arch User Repository (AUR) has a massive collection of high-performance GPU code and pretty much the latest functioning drivers, both open source and proprietary / "non-free" ones. And so far they seem much more responsive than Fedora to bug reports in GPU things.

**Comment by znmeb** [comment]
I'm back to this (getting OpenCL to work on Linux for the AMD Bonaire) for another day or so. I'm still on Arch Linux. The context this time is that I've ordered one of the Movidius (now Intell) $79US "deep learning" computer vision USB sticks. It runs "caffe" and the training needs a GPU for reasonable training times.

As far as I can tell the only requirement for an OpenCL port of caffe on an AMD GPU is ViennaCL. When I downloaded the ViennaCL manual, it noted several bugs in double precision, but single precision may be working and I may be able to train neural nets as a result.

The USB device is back-ordered; I don't have a ship date yet but it could be 28 August from what I've been able to find. So I'm only going to give this latest round of testing a day or so before moving on to training *small* models on the CPU.

**Comment by znmeb** [comment]
I finally have `gpuR` working on the AMD "Bonaire" GPU. It turns out that you need to have the AMD proprietary libraries installed; the open source ones are riddled with bugs and there's not much (if any) effort going towards fixing OpenCL there.

The proprietary libraries are only supported on Ubuntu 16.04 LTS and RHEL/CentOS 7. There are workarounds posted [here](https://github.com/BVLC/caffe/issues/5804#issuecomment-318789942) for Fedora 25/26 (previous / current) and Arch. I'm on Arch.

I'll be writing all of this up on my blog; it's been a long and frustrating journey, as scanning the dates on this issue show. ;-)

**Comment by znmeb** [comment]
You can close this - you might want to put a note in the documentation that AMD GPUs on Linux require the AMD proprietary OpenCL libraries - the open source ones don't work.

**Comment by scottkosty** [comment]
@znmeb just wanted to say thanks for all of your research on this topic. I'm just following for now, but I have an AMD (FirePro W4100) and eventually want to look into a mesa solution. Hopefully in the future things get patched up. Thanks again for posting all of your findings!

**Comment by cdeterman** [comment]
@znmeb I am currently testing the pocl 1.0 release.  Could you confirm if AMD GPUs on Linux work with it?  I intend to close this issue but I want to address your last point here before I make any notes in the documentation.

**Comment by znmeb** [comment]
@cdeterman POCL and the AMD GPU are two different implementations of the OpenCL standard. I'll test them both with your "develop" branch.

**Comment by znmeb** [comment]
Test is done - logfile at <https://gist.github.com/znmeb/98aab32fdc596fd5db4700148005d9c5>

Environment: gpuR is from the GitHub develop branch
```
> library(gpuR)
Number of platforms: 2
- platform: Advanced Micro Devices, Inc.: OpenCL 2.0 AMD-APP (2482.3)
  - context device index: 0
    - Bonaire
- platform: The pocl project: OpenCL 1.2 pocl 1.1-pre, LLVM 5.0.0
  - context device index: 0
    - pthread-AMD FX(tm)-8350 Eight-Core Processor
checked all devices
completed initialization
gpuR 2.0.1

Attaching package: ‘gpuR’

The following objects are masked from ‘package:base’:

    colnames, pmax, pmin, svd

```

**Comment by cdeterman** [comment]
AH!  It looks like it is just having issues with my custom methods where check the device type.  I neglected to change the use of the `deviceType`, `gpuInfo`, and `cpuInfo` functions that I updated in version 2.0.0.  Please try again with the `develop` branch.

**Comment by znmeb** [comment]
Re-run is at <https://gist.github.com/znmeb/7266668ac87768855f633291be30b1de>

**Comment by cdeterman** [comment]
@znmeb I believe I fixed the last few errors in your output.  Please try once more when convenient.

**Comment by znmeb** [comment]
Looks like it's working <https://gist.github.com/znmeb/5373763312b095c96a402cbb9eec4d63>. Is there any way you can suppress those compiler messages? They look like notes / warnings, not errors.

**Comment by cdeterman** [comment]
@znmeb possibly, I will need to look at see what flags I can pass in to suppress them.  It is something I did want to do as the output is definitely annoying.  I will create a new issue for this.  Are you satisfied with me closing this issue then?

**Comment by znmeb** [comment]
Yep - it's passing all the tests.
