### ISSUE TITLE
Installation problem windows 7

### ISSUE THREAD

**Issue by 01000001** [cdeterman/gpuR#80]
Could someone tell me what I'm doing wrong during installation?

Trying to install the package on windows for AMD SDK, setting the variables as:

> Sys.setenv(OPENCL_INC =   "C:/Users/acsala/AMD APP SDK/3.0/include/SDKU")
> Sys.setenv(OPENCL_LIB32 = "C:/Users/acsala/AMD APP SDK/3.0/lib/x86")
> Sys.setenv(OPENCL_LIB64 = "C:/Users/acsala/AMD APP SDK/3.0/lib/x86_64")

I got the following error message in R:

install.packages('gpuR')
Installing package into ‘C:/amc.intra/users/A/acsala/home/R/library’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘gpuR’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘gpuR’

trying URL 'https://cran.rstudio.com/src/contrib/gpuR_1.2.1.tar.gz'
Content type 'application/x-gzip' length 451127 bytes (440 KB)
downloaded 440 KB

* installing *source* package 'gpuR' ...
** package 'gpuR' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/AMC~1.INT/users/A/acsala/home/R/include" -DNDEBUG -I. -I../inst/include -DCL_USE_DEPRECATED_OPENCL_1_2_APIS   -I"C:/amc.intra/users/A/acsala/home/R/library/Rcpp/include" -I"C:/amc.intra/users/A/acsala/home/R/library/RcppEigen/include" -I"C:/amc.intra/users/A/acsala/home/R/library/RViennaCL/include" -I"H:/R/win-library/3.3/BH/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
g++.exe: error: CreateProcess: No such file or directory
make: *** [RcppExports.o] Error 1

**Comment by cdeterman** [comment]
@01000001 I'm not sure at the moment.  Could you try installing the current `develop` version with `devtools::install_github('cdeterman/gpuR', ref = 'develop')`?  You shouldn't even need to set the environmental variables with that version.

**Comment by 01000001** [comment]
@cdeterman Thank you for your answer! In the end I figured it was a mistake with about the g++ compiler pointer.

Now the package is installed and it works under 32bit R 3.3.2

> R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> Copyright (C) 2016 The R Foundation for Statistical Computing
> Platform: i386-w64-mingw32/i386 (32-bit)

Unfortunately it crashes my R session when I try to load it under 64bit

> R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> Copyright (C) 2016 The R Foundation for Statistical Computing
> Platform: x86_64-w64-mingw32/x64 (64-bit)

But I'll go ahead and use the 32bit version. Thank you for your help with the installation!
