### ISSUE TITLE
Transpose doesn't work on non-square matrices

### ISSUE THREAD

**Issue by 01000001** [cdeterman/gpuR#82]
Just discovered that transpose doesn't work correctly on non-square matrices:

```
set.seed(100)

A = matrix(rnorm(10000), nrow = 100, ncol = 110)

dim(A)
[1] 100 110

tA = gpuR::t(A)

dim(tA)
[1] 110 100

tA[1:10,1]
[1] -0.50219235 -0.33292335  0.02817177 -1.85544523 -1.28482865 -1.44628746
 [7]  1.93423814  0.50714218 -0.31551805  0.17749926

#same on vcl matrix
vclA = vclMatrix(A)
tvclA = gpuR::t(vclA)

dim(tvclA)
[1] 110 100

tvclA[1:10,1]
 [,1]
 [1,]    0
 [2,]    0
 [3,]    0
 [4,]    0
 [5,]    0
 [6,]    0
 [7,]    0
 [8,]    0
 [9,]    0
[10,]    0

```
Anyone any solutions?

**Comment by cdeterman** [comment]
@01000001 I believe I fixed this in the 'develop' version.  Please try installing `devtools("cdeterman/gpuR", ref = 'develop')` and try the transpose again.

**Comment by cdeterman** [comment]
@01000001 did you ever get a chance to evaluate the develop version?

**Comment by cdeterman** [comment]
@01000001 I have confirmed that it works locally for me using the `develop` version so I will be closing this issue.  I can reopen if you continue to encounter problems.
