### ISSUE TITLE
How to use gpuR to take the inverse of a matrix

### ISSUE THREAD

**Issue by XiaobaoZhu** [cdeterman/gpuR#84]
I wonder, how to use gpuR to take the inverse of a matrix. Which function should be used. If no such function, Can you give me some suggestion for these type of computing?

**Comment by cdeterman** [comment]
@XiaobaoZhu I believe you are looking for `solve`.

**Comment by XiaobaoZhu** [comment]
Yes I am looking for solve, but still no result

**Comment by cdeterman** [comment]
I should be implemented in both the currently released version and by `develop` branch.  What are you seeing?  Can you provide your `sessionInfo()`.

**Comment by XiaobaoZhu** [comment]
following is my result:
======================================
> ga<-gpuMatrix(c(1:16),nrow = 4,ncol = 4)
> gb<-diag(4)
> solve(ga,gb,gc)
Error in solve.default(ga, gb, gc) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
> gc<-solve(ga,gb)
Error in solve.default(ga, gb) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
> str(ga)
 int [1:4, 1:4] 1 2 3 4 5 ...
> str(gb)
 num [1:4, 1:4] 1 0 0 0 0 1 0 0 0 0 ...
> 
==========================================
did I made any mistake?

**Comment by cdeterman** [comment]
@XiaobaoZhu there are a few problems.  

1. You are showing a `gc` object without it ever being defined.
2. You are passing a `gpuMatrix` and `matrix` object to `solve` which I don't have methods defined for mixed methods.  It is defaulting to the base `solve` method where it is converting the `gpuMatrix` back to a regular `matrix` object.
3. Your test matrix is singular and therefore cannot be inverted.

A more definite example would be this:

```r
library(gpuR)

set.seed(123)
ga <- gpuMatrix(rnorm(16),nrow = 4,ncol = 4, type = "float")
gb<-gpuMatrix(diag(4), nrow =4, ncol=4, type = "float")

# passing diagonal matrix
gc <- solve(ga, gb)
gc[]

# also just pass the one matrix
gc <- solve(ga)
gc[]
```

**Comment by XiaobaoZhu** [comment]
Thank you very much.

**Comment by XiaobaoZhu** [comment]
May I ask an additional question about solve? Does this gpuR solve using GPU computing? when we use solve, how can system know which 'solve' is called(R system has an inter built solve function).

**Comment by cdeterman** [comment]
@XiaobaoZhu if it is a `gpuMatrix` or `vclMatrix` it is always using the GPU for computing.  Anything else (unless another GPU package) is using the CPU.

**Comment by XiaobaoZhu** [comment]
Thank you very much! You really helped me much!
