### ISSUE TITLE
OSX failing with develop branch

### ISSUE THREAD

**Issue by cdeterman** [cdeterman/gpuR#90]
User installed the `develop` branch and saw the resulting error on a OSX machine.

```r
gpuA <- vclVector(a, type = "float")
Error in cpp_cpuInfo(platform_idx, device_idx) : device is not a CPU
```

**Comment by cdeterman** [comment]
@clarkfitzg I believe the `vclVector` problem is fixed but I appear to have other unit test errors I need to resolve.

**Comment by clarkfitzg** [comment]
Yes, `vclVector` works now.

**Comment by cdeterman** [comment]
@clarkfitzg can you confirm in the `svd` function works for you from `develop`?

**Comment by clarkfitzg** [comment]
Doesn't look like it.

```
> n = 100
> X = vclMatrix(rnorm(n * n), nrow = n, ncol = n)
> s = svd(X)
ViennaCL: FATAL ERROR: Kernel start failed for 'givens_prev'.
ViennaCL: Smaller work sizes could not solve the problem.
Error in cpp_vclMatrix_svd(x@address, D@address, U@address, V@address,  :
  ViennaCL: FATAL ERROR: CL_INVALID_WORK_GROUP_SIZE
 The supplied work group size is invalid. If you have set this value manually, please reconsider your choice.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net and supply at least the following information:
 * Operating System
 * Which OpenCL implementation (AMD, NVIDIA, etc.)
 * ViennaCL version
Many thanks in advance!
>
```

I'm on this commit in `develop`:

```
commit fb6f39cd766b658ec9f02a1faa65c590ed8b5b12
Author: Determan <DetermanC@schneider.com>
Date:   Thu Aug 31 10:46:29 2017 -0500
```

**Comment by cdeterman** [comment]
@clarkfitzg thank you, that confirms what I have been seeing.  If you have a moment, could you try to re-install the current release of `gpuR` from CRAN and try `svd` again?  I want to know if it was always broken or not.

**Comment by clarkfitzg** [comment]
Just tested, the CRAN version works:

```
> str(s)
List of 3
 $ d:Formal class 'fvclVector' [package "gpuR"] with 6 slots
  .. ..@ address        :<externalptr>
  .. ..@ .context_index : int 1
  .. ..@ .platform_index: int 1
  .. ..@ .platform      : chr "Apple"
  .. ..@ .device_index  : int 1
  .. ..@ .device        : chr "Iris Pro"
 $ u: flt [1:100, 1:100] 0.151 0.074 -0.12 -0.046 -0.108 ... $ v: flt [1:100, 1:100] -0.123 0.009 0.041 0.067 -0.088 ...>
```

**Comment by cdeterman** [comment]
@clarkfitzg thank you very much.  One last thing, can you see if the same device is used in the `develop` version?  I apologize for the back and forth but I don't have a Mac available to test these things.  Basically I want to see if the `.device` field is still `"Iris pro"`.  I suspect the problem is that with the `develop` version I now have it explicitly instantiating all possible devices and I think you may be using the CPU by default in the `develop` version which results in the failed svd kernel.

**Comment by clarkfitzg** [comment]
Looks like you're spot on. On the `develop` version:

```
> n = 100
> X = vclMatrix(rnorm(n * n), nrow = n, ncol = n, type = "float")
> X
An object of class "fvclMatrix"
Slot "address":
<pointer: 0x7fd011545f10>

Slot ".context_index":
[1] 1

Slot ".platform_index":
[1] 1

Slot ".platform":
[1] "Apple"

Slot ".device_index":
[1] 1

Slot ".device":
[1] "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz"
```

**Comment by cdeterman** [comment]
@clarkfitzg I'm not sure about the timeline for the fix on the CPU implementation.  Could you install the `develop` version once more and change the context with `setContext(2L)`?  Then try the `svd` call once more.  I want to confirm that it will still work with the new version.

**Comment by clarkfitzg** [comment]
Sure, I'll try to circle back to this on Monday.

**Comment by clarkfitzg** [comment]
This works on latest commit on `dev`:

```
> setContext(2L)
> n = 100
> X = vclMatrix(rnorm(n * n), nrow = n, ncol = n, type = "float")
> svd(X)
$d
An object of class "fvclVector"
Slot "address":
<pointer: 0x7fee66179810>

Slot ".context_index":
[1] 2

Slot ".platform_index":
[1] 1

Slot ".platform":
[1] "Apple"

Slot ".device_index":
[1] 1

Slot ".device":
[1] "Iris Pro"


$u
An object of class "fvclMatrix"
Slot "address":
<pointer: 0x7fee6351a440>

Slot ".context_index":
[1] 2
```

**Comment by cdeterman** [comment]
Mac now builds and all tests are passing
