### ISSUE TITLE
Make matrices/ vectors `float` by default?

### ISSUE THREAD

**Issue by dselivanov** [cdeterman/gpuR#92]
I would like to start discussion about default precision of GPU matrices and vectors. At the moment they are `double`. My proposal is to make `float` as default choice. Rational is following:

1. Most mass-market cards support only `float`. So creating vectors throws error.
1. Even if they support `double`, performance suffers a lot - 10x+ .For example [wiki about 10* GTX series](https://en.wikipedia.org/wiki/GeForce_10_series#GeForce_10_.2810xx.29_series)

**Comment by cdeterman** [comment]
I personally don't have an issue with this.  Hopefully a few others will chime in with opinions.

**Comment by beibeijiang** [comment]
I prefer `double` as default.

**Comment by dselivanov** [comment]
Why? Double 10x+ slower than float and occupy 2x more ram. Please clarify a
bit.

20 сент. 2017 г. 22:33 пользователь "Beibei" <notifications@github.com>
написал:

**Comment by beibeijiang** [comment]
Double is slower but it is precise. When the standard R object converted to a gpuR object, as a gpuR user, I hope the package I use would keep my data type by default and would not let me lose anything. :)
Maybe I never have RAM problem with my GPUs, so 2x more RAM is not a problem for me.

**Comment by dselivanov** [comment]
Ok, but why use gpu if it will be on par with cpu for double? IMO precision
issues with float are highly overestimated and occur rarely in practice.

20 сент. 2017 г. 23:19 пользователь "Beibei" <notifications@github.com>
написал:

**Comment by beibeijiang** [comment]
I tested the performance 2 years ago. My small calculation with `gputools` on one graphics card (Tian black) needs the same time( almost 24 hours) as I run on 96 cores (Intel(R) Xeon, currently, cant' check the detail).  Then my single project has thousand times more calculation. It is better for me to use GPUs.

About the precision, my understanding is if my data is highly discrete (with extremely big and small values), it is easy for me to lose one decimal part during thousands of times addition.

**Comment by cdeterman** [comment]
@beibeijiang I think your point reinforces that perhaps `float` would be a better default.  Your situation is rather unique with so many iterative calculations.  In your case, it would simply require adding the line `options(gpuR.default.type="double")` and nothing else would change.

**Comment by dselivanov** [comment]
This is because of Titan black - it offers very good double precision flops 1/3 of float. For example gtx 980 which much more mass market has double precision performance = 1/32 float! 
Regarding your case with highly contrast values I agree - there will be issue. But still this case is not common. And good default values are always trade-off between having good general performance and number of exceptions.
Thanks for sharing your opinion anyway!

**Comment by beibeijiang** [comment]
@cdeterman How could I make you feel so? I am really bad at giving examples. :-0

As a user, I prefer the default is no change of the data type from standard R object to gpuR object. Unless R offers float type. People who can only program with R may confuse if they have GPU supporting double precision? Maybe I could discuss with my colleagues what they think since I recommended gpuR to them.

By the way, @dselivanov Thanks for the information. Now I am happy with all GPUs we have.

**Comment by cdeterman** [comment]
@beibeijiang would be happy to hear additional perspectives from your colleagues.  The reason your example makes me think `float` may actually be a better default is because you are conducting so many iterations.  I would not expect this type of experiment to be typical of most users.  

Additionally, my main point before was to also reinforce that regardless of the default, it is quite trivial to change the default in a user session by setting the global option `gpuR.default.type`.

**Comment by cdeterman** [comment]
@beibeijiang did your colleagues have anything additional to add to this topic?  I think I will end up changing the default to 'float' unless I have a convincing reason otherwise.

**Comment by beibeijiang** [comment]
I showed them the second comparison in issue #96 and also mentioned your suggestion `options(gpuR.default.type="double")`  to them. They were surprised about the difference (0.013 as shown in issue #96) but they don't mind if you want to change it, as long as you don't remove(or say, give up exporting)  some functions in the previous versions.

**Comment by cdeterman** [comment]
@beibeijiang  what functions would they be concerned about?  I export all functions for both `float` and `double` precision.

**Comment by beibeijiang** [comment]
I think the comment is not related to `gpuR` . I guess they were talking about some general problems caused by other updated packages.

**Comment by cdeterman** [comment]
Well, I neglected to make the change over to `float` during the latest submission to CRAN.  Given that the submission of this package is more of a hassle (it requires manual checking by CRAN members) I will wait until the 2.1.0 release to make this change.  Therefore, I will reopen and retag this issue accordingly.
