### ISSUE TITLE
gpuR with Windows 7 with Intel HD Graphics 5500 and AMD Radeon R7 M260X

### ISSUE THREAD

**Issue by lucavignali** [cdeterman/gpuR#93]
I tried to use the gpuR library on my PC from RStudio. The following code works but I can see that CPU only is used. From TechPowerUp GPU I can see both GPUs unused. To my understanding only the AMD is OpenCL compatible, is there a gpuR configuration to force the usage of the AMD Radeon?
Thanks,

```r
library(gpuR)
detectGPUs()

ORDER = 3000
A = matrix(rnorm(ORDER^2), nrow=ORDER)
B = matrix(rnorm(ORDER^2), nrow=ORDER)

# Time required to compute the A * B matrix product.
CPUtime <- system.time(C <- A %*% B) 
gpuA = gpuMatrix(A, type="double")
gpuB = gpuMatrix(B, type="double")
GPUtime <- system.time(gpuC <- gpuA %*% gpuB)
# Gain GPU over CPU for the elapsed time
CPUtime[3]/GPUtime[3]
```

**Comment by cdeterman** [comment]
@lucavignali can you provide the output of `listContexts()`.  Also, what version of `gpuR` are you using `sessionInfo()`?  Can you also comfirm, do you have two GPUs in addition to  the CPU?

**Comment by lucavignali** [comment]
Here you can find the output of listContent() and gpuR version from sessionInfo. I confirm that I have two video adapters: AMD Radeon R7 M260X and Intel HD Graphics 5500 that are both graphical processing units. However, according to listContext(), the detectGPUs command return 1.

**> listContexts()**
  context                                                  platform platform_index                                   device device_index device_type
1       1                         Intel(R) Corporation: OpenCL 2.0               0 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz            0         cpu
2       2 Advanced Micro Devices, Inc.: OpenCL 1.2 AMD-APP (1573.4)              1                                    Oland            0         gpu
3       3                         Intel(R) Corporation: OpenCL 2.1               2 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz            0         cpu

**sessionInfo()**
other attached packages:
[1] gpuR_1.2.1

**Comment by cdeterman** [comment]
@lucavignali yes, this I believe is a bug in the current CRAN version.  Please try installing my `develop` version with `devtools::install_github('cdeterman/gpuR', ref = 'develop')`.  I am working hard to get the necessary updates done so I can finally release the newest version.

**Comment by lucavignali** [comment]
Hi, let me share the updated infos below. However I can't see any usage of the GPU through the TechPowerUp GPU tool. Is there any way to force gpuR to utilize the device labelled as "context 2"?

**> listContexts()**
context                                                  platform platform_index                                   device device_index device_type
1       1                         Intel(R) Corporation: OpenCL 2.0               0 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz            0         cpu
2       2 Advanced Micro Devices, Inc.: OpenCL 1.2 AMD-APP (1573.4)              1                                    Oland            0         gpu
3       3 Advanced Micro Devices, Inc.: OpenCL 1.2 AMD-APP (1573.4)              1 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz            0         cpu
4       4                         Intel(R) Corporation: OpenCL 2.1               2 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz            0         cpu

**sessionInfo()**
other attached packages:
[1] gpuR_1.2.3

**Comment by cdeterman** [comment]
@lucavignali yes, with the `develop` version you can set the context with the function `setContext`.  In your case, you would simply call

```r
setContext(2L)
```

You can verify which device is currently active with 

```r
currentDevice()
```

**Comment by cdeterman** [comment]
@lucavignali can you confirm if my previous comment addressed the issue?

**Comment by lucavignali** [comment]
Yes absolutely for me you can close the issue. I thought I wrote it in my previous comment. I apologize.

Inviato da iPhone

**Comment by cdeterman** [comment]
@lucavignali thanks, please feel free to submit any future issues.
