### ISSUE TITLE
cov() supports only one matrix

### ISSUE THREAD

**Issue by beibeijiang** [cdeterman/gpuR#95]
Hi Charles,

Does cov() only support `cov(gpuA)` ? No `cov(gpuA, gpuB)`? 

I see the description for this function as follows:
`cov(x, y = NULL, use = NULL, method = "pearson")`

`x`  A gpuR object
`y`  Not used
`use`  Not used
`method`  Character string indicating with covariance to be computed.

**Comment by beibeijiang** [comment]
My answer to my question: no, it doesn't supprot two objects.

**Comment by cdeterman** [comment]
@beibeijiang yes, you are correct that it is not yet supported.  If I come across some concise, vectorized, matrix notation to accomplish it then I will.  I simply haven't dedicated my time towards this particular aspect as it was not previously a hot topic for users.

**Comment by beibeijiang** [comment]
I also didn't realize it until I have to rewrite one old R package based on `gputools`.  Anyway, I am glad that you know the request now and looking forward to having it in the feature. Great thanks to all your work on helping us use GPU easily.

**Comment by cdeterman** [comment]
@beibeijiang I think I can get an implementation working but it likely won't be as performant as it could be.  My intention is write the full OpenCL kernels for the correlation/covariance calculations but I really want to get 2.0.0 released so I will need to push that back until afterwards.  I will push out a quick version of `cov("gpuMatrix", "gpuMatrix")` and `cov("vclMatrix","vclMatrix")` prior to that release.

**Comment by beibeijiang** [comment]
Thanks a lot! You are great!
