### ISSUE TITLE
Is t(x)%*%x not equeal to crossprod(x)?

### ISSUE THREAD

**Issue by beibeijiang** [cdeterman/gpuR#96]
Hi Charles,

I did something like the following and got weird output. Did I use these wrong?

```{r compare}
library(gpuR)
set.seed(123)
B <- matrix(rnorm(200, mean = 10, sd = 100), ncol = 20)
gpuB <- gpuMatrix(B, type = "float")
temp1 <- t(gpuB) %*% gpuB
temp2 <- crossprod(gpuB)
max(abs(temp1 - temp2))
[1] 121086


temp3 <-  crossprod(B)
max(abs(temp2[] - temp3))
[1] 0.01331507


currentDevice()
$device
[1] "Intel(R) Iris(TM) Graphics 6100"

$device_index
[1] 1

$device_type
[1] "gpu"
```

**Comment by cdeterman** [comment]
What version of `gpuR` are you using?  I don't get the difference you show when comparing `temp1` and `temp2`.  The second comparison is basically comparing `float` and `double` precision.  You should expect to see a small difference.

**Comment by beibeijiang** [comment]
packageVersion("gpuR")
[1] ‘1.2.1’

The second comparison is for myself. Sorry.

**Comment by cdeterman** [comment]
Try with the current `develop` version `devtools::install_github('cdeterman/gpuR', ref = 'develop')`.  I am nearly ready to release the next version `2.0.0`.

**Comment by cdeterman** [comment]
@beibeijiang did the `develop` version solve the issue?

**Comment by beibeijiang** [comment]
Yes, I just tried the developed version and it solves the issue. I think you can close it. 

Sorry for getting back late.
