### ISSUE TITLE
Bug in GEMV: result wrong dimension

### ISSUE THREAD

**Issue by chrism0dwk** [cdeterman/gpuR#97]
I think I've discovered a critical bug in the GEMV implementation in gpuR version 2.0.0.  

Example: multiply 3x2 matrix 'x' by a vector of length 2 'y':
```
> x = vclMatrix(matrix(1:6,ncol=2),type='float')
> y = vclVector(1:2, type='float')
> z = x%*%y
> z[]
[1]  9 12
```
The result 'z' is of length length(y), rather than nrow(x).   

If I change the dimensions of the data structures such that 'x' is 3x2 and 'y' is length 3:
```
> x = vclMatrix(matrix(1:6,ncol=3),type='float')
> y = vclVector(1:3, type='float')
> z = x%*%y
> z[]
[1] 22 28 0
```
Again, the result is of length(y), not nrow(x).

Cheers,

Chris

System spec
--
R version 3.4.1
gpuR version 2.0.0 (CRAN)
CentOS 7.5
CUDA 9.0 with NVIDIA Quadro GP100 card.

**Comment by cdeterman** [comment]
Thank you for reporting. I completely forgot my unit tests for gemv and this is what I get.  I will commit a bug fix shortly.

**Comment by chrism0dwk** [comment]
Many thanks for fixing this so quickly!  A great help to my research :)

Chris

**Comment by cdeterman** [comment]
No problem, in this case it was an easy fix that you pointed out.  Please let me know if you encounter any other issues.  Glad the package is useful to you.
