### ISSUE TITLE
t,vclMatrix on non-square matrix incorrect

### ISSUE THREAD

**Issue by chrism0dwk** [cdeterman/gpuR#99]
Test case:
```
X = vcl(matrix(1:6,ncol=2), type='float')
> X[]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
> t(X)[]
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0

I wonder if this is related to #97?

Cheers,

Chris

**Comment by chrism0dwk** [comment]
N.B. t(X) on a square matrix does appear to work.

**Comment by cdeterman** [comment]
@chrism0dwk odd, it is working for me.  I assume you still have 2.0.0 installed or do you have 2.0.1 from github?  Also, could you provide the output of `listContexts()`

**Comment by chrism0dwk** [comment]
Ah, sorry.  I realised I was on another platform where I was using v. 2.0.0.  I can confirm this bug does not exist in 2.0.1.

Apologies for the time-waste!

C
